src/cwrapper.cpp
@isuruf, for me this still works and there are no leaks.
=> Cwrapper polish

src/add.cpp, src/mul.cpp, src/pow.cpp, src/tests/basic/test_arit.cpp
Fix bug in mul_expand because of failure to initialize variable
Fixes #370.
=> More bug fixes for pow and expand

src/add.cpp, src/tests/basic/test_basic.cpp
Handle case where result of arg diff is a Add
=> Fix Add::diff

src/pow.cpp, src/tests/basic/test_arit.cpp
Added check for negative exponent and also proper handling of such
cases.
Fixes #371
=> Allows expand to work with pow instances with negative powers

src/basic.h, src/eval_double.cpp
=> Use single dispatch for eval_double()

bin/test_travis.sh, csympy/CMakeLists.txt
=> Run Python tests when installed using make install

.travis.yml, benchmarks/CMakeLists.txt, bin/test_travis.sh, csympy/lib/CMakeLists.txt, src/CMakeLists.txt, src/tests/basic/CMakeLists.txt, src/tests/cwrapper/CMakeLists.txt, src/tests/eval/CMakeLists.txt, src/tests/matrix/CMakeLists.txt, src/tests/ntheory/CMakeLists.txt, src/tests/printing/CMakeLists.txt, src/teuchos/CMakeLists.txt
With this we can use `-DBUILD_SHARED_LIBS=on/off` to make csympy shared lib on/off.
=> Link teuchos and other libraries to csympy and make teuchos static

src/cwrapper.cpp, src/cwrapper.h, src/tests/cwrapper/test_cwrapper.c
Implemented integer_get_si, integer_get_ui and integer_get_mpz with simple tests.
=> Implementing get methods in cwrapper

.gitignore
=> Added eval_double1 to .gitignore

.mailmap, AUTHORS
@SankaGIT @abinashmeher999, let me know if your name and email address are correct.
=> Added Sanka and Abinash to AUTHORS. Welcome to CSymPy!

bin/install_travis.sh
Issue in miniconda seems to be fixed now.
Keeping the hack, fails the tests in shippable.
=> Remove hack for miniconda glibc issue

src/cwrapper.h
Now they accurately reflect how things are implemented.
=> Clarify the comments in C wrappers

src/basic.h
Some spelling mistakes:
Sublcasses -> Subclasses
=> Typos error

src/eval_double.cpp
This PR is to see whether changing from Visitor to BaseVisitor will affect the performance of EvalDoubleVisitor. If not, I'll change all the Visitors to BaseVisitor.
For me, I noticed no slowdown using gcc.
@certik
=> [WIP] Change EvalDoubleVisitor to use BaseVisitor

src/functions.cpp, src/tests/basic/test_functions.cpp
As seen in #427 
@sushant-hiray @certik @isuruf
=> Replace x with getarg() in Inverse hyperbolic Functions

AUTHORS, README.md, bin/test_travis.sh, doc/index.rst, doc/style_guide.md
This only renames things in text files. No code is touched yet.
=> Rename CSymPy to SymEngine

csympy/lib/csympy.pxd, csympy/lib/csympy_wrapper.pyx, src/complex.h, src/rational.h, src/tests/basic/test_basic.cpp
These were changes introduced in #408. Rest of the code in #408 will be implemented in Sage.
=> Improve Python Wrappers

.gitignore
Updated .gitignore for src/tests/eval/test_eval_double
=> Updated .gitignore for src/tests/eval/test_eval_double

AUTHORS
@aktech Could you check and let me know if any changes needed?
=> Added AMiT to AUTHORS. Welcome to SymEngine!

src/complex.h, src/eval_double.cpp, src/eval_double.h, src/tests/eval/test_eval_double.cpp
Added a new method to evaluate in `std::complex<double>`.
Also found a few bugs and edited them in this PR.
=> Added eval_complex_double

src/functions.cpp, src/number.h, src/pow.cpp, src/real_double.cpp, src/real_double.h, src/tests/basic/test_functions.cpp
I added the basic functionality for sin and cos. 
@certik @sushant-hiray take a look.
=> Evaluate functions for RealDouble automatically

benchmarks/add1.cpp, benchmarks/expand1.cpp, benchmarks/expand2.cpp, benchmarks/expand2b.cpp, benchmarks/expand3.cpp, src/basic.h, src/constants.cpp, src/functions.cpp, src/pow.cpp, src/rational.cpp, src/rational.h, src/tests/basic/test_arit.cpp, src/tests/basic/test_basic.cpp, src/tests/basic/test_functions.cpp, src/tests/basic/test_poly.cpp, src/tests/basic/test_subs.cpp
Following
```
RCP<const Basic> x = rcp(new Symbol("x"));
RCP<const Basic> x = rcp(new Integer(2));
```
were converted to
```
RCP<const Basic> x = symbol("x");
RCP<const Basic> x = integer(2);
```
cc @certik @isuruf
=> Changed rcp(new(symbol("*") to symbol("*") in tests

CMakeLists.txt, README.md
Add OpenMP support so that we can use it for parallel algorithms.
=> Openmp support

src/sparse_matrix.cpp
Fixed TODO in sparse_matrix.cpp but this commit seems to break tests. 
There are two more binary search implementation TODOs, if we can fix this so that tests pass we can implement the other two.
cc @thilinarmtb
=> Fixed TODO: Implement binary search in sparse_matrix.cpp

CMakeLists.txt
=> Add MPFR as a Piranha dependency

.travis.yml, symengine/printer.cpp, symengine/printer.h, symengine/python/symengine/__init__.py, symengine/python/symengine/lib/symengine_wrapper.pyx, symengine/python/symengine/tests/test_eval.py, symengine/python/symengine/tests/test_sympy_conv.py, symengine/tests/printing/test_printing.cpp
=> Improve RealMPFR and ComplexMPC

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/tests/cwrapper/test_cwrapper.c
These are polished patches from #495. Ready for review.
=> C Wrappers Refactoring

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/tests/cwrapper/test_cwrapper.c
I checked and there are no memory leaks in `test_cwrapper` after addition of these wrappers.
cc @certik @isuruf
=> Added c wrapper for set_basic and free_symbols

AUTHORS
@bluescarni I hope everything is fine.
Welcome to SymEngine
=> Added Francesco to AUTHORS. Welcome to SymEngine!

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/tests/cwrapper/test_cwrapper.c
Test added.
@abinashmeher999 can you review this please? It implements the methods that you need to use to create an expression to pass to Ruby.
=> Implement basic_new_heap() and basic_free_heap()

.gitignore, symengine/ruby/lib/symengine.rb, symengine/ruby/lib/symengine/iruby.rb, symengine/ruby/notebooks/Gemfile, symengine/ruby/notebooks/README.md, symengine/ruby/notebooks/beginner.ipynb, symengine/ruby/symengine.gemspec
- Added an IRuby notebook for beginners
- Added a README redirecting to instructions on setting up IRuby
- Added `iruby` as a development dependency
=> Added a beginner IRuby notebook

symengine/python/symengine/__init__.py, symengine/python/symengine/lib/symengine_wrapper.pyx, symengine/python/symengine/tests/test_matrices.py, symengine/python/symengine/tests/test_sympy_conv.py
@isuruf some of these are good to have so that the experience is much better inside Python (and thus also Sage).
=> Improvements to the Python wrappers

symengine/python/symengine/lib/symengine_wrapper.pyx
This can be used when we know that the DenseMatrix is filled up
=> Initialise DenseMatrix with no elements

symengine/tests/ntheory/test_ntheory.cpp
=> Use RCPBasicKeyEq to simplify a test

symengine/python/symengine/__init__.py, symengine/python/symengine/lib/symengine.pxd, symengine/python/symengine/lib/symengine_wrapper.pxd, symengine/python/symengine/lib/symengine_wrapper.pyx, symengine/python/symengine/tests/test_functions.py, symengine/python/symengine/tests/test_sympy_conv.py
I've added Log and Trig Functions.
Let me know if it's okay, so I can start on Hyperbolic Functions.
=> Wrap SymEngine classes in Python

symengine/dense_matrix.cpp, symengine/matrix.h, symengine/python/symengine/lib/symengine.pxd, symengine/python/symengine/lib/symengine_wrapper.pyx, symengine/python/symengine/tests/test_matrices.py, symengine/tests/matrix/test_matrix.cpp
@moorepants, this is what we need for PyDy. Now I am implementing the differentiation with respect to a function symbol.
=> Implement Jacobian

symengine/python/symengine/lib/symengine_wrapper.pyx, symengine/python/symengine/tests/test_matrices.py
An error made this only support square matrices.
=> Fix matrix multiplication

symengine/add.cpp, symengine/dict.cpp, symengine/dict.h, symengine/functions.cpp, symengine/mul.cpp
@certik @Sumith1896 
Fixes #529
=> Templated functions for **_eq and **_compare

benchmarks/expand6.cpp, cmake/UserOverride.cmake, symengine/printer.cpp, symengine/printer.h, symengine/tests/basic/test_basic.cpp, symengine/tests/cwrapper/test_cwrapper.c, symengine/visitor.cpp, symengine/visitor.h
This PR fixes most of the issues from #536 in a way that can be merged now.
=> Add polished changes needed for Intel

.travis.yml, symengine/python/symengine/lib/CMakeLists.txt, symengine/python/symengine/lib/symengine_wrapper.pyx
Previously testing was not done in Travis due to a bug.
=> Test MPFR and MPC with Python

CMakeLists.txt, appveyor.yml
This installs MPIR, our cmake passes and it starts compiling our code.
So this in my opinion can be merged to master, and then we can start fixing the problems in our code so that it compiles on MSVC.
=> Add CI testing on AppVeyor

.travis.yml, appveyor.yml, bin/install_travis.sh
That way if upstream server times out, we are not affected.
=> Host the mpir-2.7.0.zip on our github

symengine/add.cpp, symengine/basic-inl.h, symengine/basic.cpp, symengine/basic.h, symengine/functions.cpp, symengine/mul.cpp, symengine/pow.cpp, symengine/symengine_rcp.h, symengine/tests/rcp/CMakeLists.txt, symengine/tests/rcp/test_rcp.cpp, symengine/visitor.cpp
Benchmarks do not seem to be affected.
=> Implement EnableRcpFromThis base class

symengine/add.cpp, symengine/tests/basic/test_subs.cpp
The test fails in master and this patch fixes it.
=> Fix a bug in subs(), add test

symengine/cwrapper.cpp, symengine/ntheory.cpp, symengine/pow.cpp, symengine/python/symengine/lib/symengine.pxd, symengine/python/symengine/lib/symengine_wrapper.pyx, symengine/rational.cpp, symengine/rational.h, symengine/tests/basic/test_arit.cpp, symengine/tests/basic/test_basic.cpp, symengine/tests/ntheory/test_ntheory.cpp, symengine/tests/printing/test_printing.cpp
=> Use object reference in Rational::from_two_ints and Rational::get_num_den

.gitignore, appveyor.yml, symengine/python/symengine/tests/test_arit.py, symengine/python/symengine/tests/test_ntheory.py
Added python testing for MSVC in Release mode.
In Debug mode, `python27_d.lib` which is the debug version of python is missing.
=> Python testing for MSVC

symengine/add.cpp, symengine/complex_double.h, symengine/complex_mpc.h, symengine/mul.cpp, symengine/number.h, symengine/pow.cpp, symengine/real_double.h, symengine/real_mpfr.h, symengine/tests/basic/test_arit.cpp, symengine/tests/basic/test_number.cpp, symengine/tests/basic/test_subs.cpp
Made changes to #542, so that there's minimal changes to get this working.
Updated comments and added direct tests for methods in `Number`
=> Automatic simplification of x * 0.0 and x ** 0.0

.travis.yml, bin/install_travis.sh, bin/test_travis.sh, symengine/python/symengine/tests/CMakeLists.txt, symengine/python/symengine/tests/test_sage.py
Testing of sage wrappers in travis with sage ubuntu package.
Installing sage using the ppa sometimes fail. So, installing is tried 3 times, but it still fails sometimes.
=> Test Sage wrappers

benchmarks/symbench.cpp, benchmarks/symbench.py, benchmarks/symbench_def.py, benchmarks/symbench_ginac.cpp, benchmarks/symbench_sage.py
```
Time for R1      SymEngine :     0.000580072 s   SymPy  :     0.379003048 s      Sage   :     0.002073050 s
Time for R2      SymEngine :     0.008193016 s   SymPy  :     0.125511169 s      Sage   :     0.073295116 s
Time for R3      SymEngine :     0.000019073 s   SymPy  :     0.000005960 s      Sage   :     0.000049114 s
Time for R5      SymEngine :     0.000005960 s   SymPy  :     0.000011921 s      Sage   :     0.011657953 s
Time for R7      SymEngine :     0.000072956 s   SymPy  :     0.026857853 s      Sage   :     0.003690004 s
Time for R8      SymEngine :     0.016391993 s   SymPy  :     0.914372921 s      Sage   :     0.163179874 s
Time for S1      SymEngine :     0.014119864 s   SymPy  :     3.081020117 s      Sage   :     0.029356956 s
Time for S2      SymEngine : …
```
=> R7 and R8 from symbench

CMakeLists.txt, cmake/FindARB.cmake, cmake/FindBFD.cmake, cmake/FindECM.cmake, cmake/FindEXECINFO.cmake, cmake/FindFLINT.cmake, cmake/FindGMP.cmake, cmake/FindMPC.cmake, cmake/FindMPFR.cmake, cmake/FindPRIMESIEVE.cmake, cmake/FindPTHREAD.cmake, cmake/FindTCMALLOC.cmake, cmake/LibFindMacros.cmake
Discussion at https://gitter.im/sympy/symengine?at=55c785047f578b465ff46f30
=> Use IMPORTED targets to force cmake to use full paths

README.md
And clarify the first section a bit.
=> Add links to wrappers into README

.travis.yml, CMakeLists.txt, bin/install_travis.sh, bin/test_travis.sh
We'll need to run the tests `WITH_PIRANHA=yes` as, at least for now, `Polynomial` will depend on `Piranha`
cc @certik @isuruf @shivamvats
=> Travis testing for Piranha dependency

benchmarks/symbench.nb
Timings in seconds
```
0.000109
0.018574
0.000044
0.000015
0.100028
0.036448
0.004581
0.162594
0.030427
3.3425
```
=> Added symbench.nb

symengine/symengine_assert.h, symengine/tests/basic/test_basic.cpp, symengine/tests/basic/test_functions.cpp, symengine/tests/basic/test_number.cpp, symengine/tests/eval/test_eval_double.cpp, symengine/tests/matrix/test_matrix.cpp, symengine/tests/ntheory/test_ntheory.cpp
=> Get rid of SYMENGINE_CHECK_THROW

AUTHORS
@bjodah I hope everything is fine.
Welcome to SymEngine!
=> Added Björn to AUTHORS. Welcome to SymEngine!

appveyor.yml, bin/appveyor-download.cmd
Based on https://gist.github.com/FeodorFitsner/508b71250295590e6408
Fixes #577
=> Retry appveyor download

symengine/add.cpp, symengine/dict.cpp, symengine/dict.h, symengine/eval_double.cpp, symengine/functions.cpp, symengine/lambda_double.h, symengine/mul.cpp, symengine/ntheory.cpp, symengine/polynomial.cpp, symengine/pow.cpp, symengine/printer.cpp, symengine/rings.cpp, symengine/visitor.cpp
I think 
```
for (auto& name : ds) {
...
}
```
can be replaced with 
```
for (const auto& name : ds) {
...
}
```
if `name` is not modified in `for` loop.
=> Use const references

.gitignore, symengine/CMakeLists.txt, symengine/series.cpp
1. Adding `benchmarks/series` to `.gitignore`.
2. Fix #653.
3. Adding `const` references.
=> Some general optimizations and fix for #653

symengine/number.h, symengine/rational.cpp, symengine/rational.h, symengine/tests/basic/test_rational.cpp
=> rational is_perfect_power() and nth_root(); change rational creator

benchmarks/CMakeLists.txt, benchmarks/series_expansion_sincos.cpp, symengine/CMakeLists.txt, symengine/basic.h, symengine/dict.h, symengine/expansion.cpp, symengine/pow.h, symengine/tests/basic/CMakeLists.txt, symengine/tests/basic/test_series_expansion.cpp
So this is the first usable version that supports the functions sin, cos, tan, cot. csc, sec, atan, asin, log, exp, sinh, cosh, tanh, asinh, atanh, lambertw.
Missing from a full feature series package:
- real coefficients
- symbolic constants, e.g. sin(1)
- rational exponents
- multivariate expressions/series
=> expression univariate series expansion with rational coefficients

symengine/complex.h
Removed redundant calculations of checking imaginary equal zero as per #676
=> Removed redundant calculations 

.gitignore
Adding
```
symengine/tests/basic/test_series_expansion
benchmarks/series_expansion_sincos
```
=> Adding executables in gitignore

symengine/rational.h
=> removed redundant checks from rational.h

symengine/functions.cpp, symengine/rational.h
marked as TODO in `functions.cpp`
=> implement Rational::neg()

symengine/add.cpp, symengine/add.h, symengine/complex.cpp, symengine/complex.h, symengine/functions.cpp, symengine/functions.h, symengine/matrix.h, symengine/mul.cpp, symengine/mul.h, symengine/polynomial.cpp, symengine/polynomial.h, symengine/pow.cpp, symengine/pow.h, symengine/rational.cpp, symengine/rational.h, symengine/series.cpp, symengine/series.h, symengine/sparse_matrix.cpp
=> increase constness

doc/design.md
Also-by: Ralf Stephan <ralf@ark.in-berlin.de>
=> documentation: merge everything from the Wiki on design plus from #445 into design.md

symengine/add.cpp, symengine/basic.h, symengine/complex_double.cpp, symengine/complex_double.h, symengine/complex_mpc.cpp, symengine/complex_mpc.h, symengine/diophantine.h, symengine/eval_double.h, symengine/expression.h, symengine/functions.cpp, symengine/lambda_double.h, symengine/monomials.cpp, symengine/mul.cpp, symengine/ntheory.cpp, symengine/number.cpp, symengine/pow.cpp, symengine/real_double.cpp, symengine/real_double.h, symengine/real_mpfr.cpp, symengine/real_mpfr.h, symengine/rings.cpp, symengine/visitor.cpp
Fixes https://github.com/symengine/symengine/issues/643
\cc @certik @isuruf
=> Include all used C++ library headers in basic.h

bin/test_travis.sh, symengine/utilities/tests/test_make_install.py, symengine/utilities/tests/test_trailing_whitespace.py
...and moved `test_trailing_whitespaces.py` and `test_make_install.py` there.
cc @certik @isuruf
=> Added symengine/utilities/tests folder, following SymPy

symengine/constants.cpp, symengine/constants.h, symengine/eval_arb.cpp, symengine/eval_double.cpp, symengine/eval_mpc.cpp, symengine/eval_mpfr.cpp, symengine/tests/eval/test_eval_arb.cpp, symengine/tests/eval/test_eval_double.cpp, symengine/tests/eval/test_eval_mpc.cpp, symengine/tests/eval/test_eval_mpfr.cpp
added symbolic constant `euler_const`
#697
=> add Euler's Constant

LICENSE
=> Update LICENSE for 2016

symengine/utilities/tests/test_code_quality.py
Sorry, the initial pull request wasn't exiting with the correct return codes.
Fixed.
=> fixed travis check, wasn't exiting correctly

.gitignore, symengine/utilities/teuchos/Teuchos_RCP.hpp
@certik is this what you were looking for?
With reference to #426.
=> rcp_static_cast() should check that the cast is valid in Debug mode

symengine/integer.cpp, symengine/mul.cpp, symengine/number.h, symengine/pow.cpp, symengine/rational.cpp, symengine/rational.h, symengine/tests/basic/test_arit.cpp, symengine/tests/printing/test_printing.cpp
Expressions like `sqrt(4)` are now automatically converted into `2`
=> Integer and Rational roots

symengine/derivative.cpp, symengine/tests/basic/test_functions.cpp
=> added derivative of gamma

symengine/basic.h
=> Fix for MSVC Warning C4003

symengine/ntheory.cpp, symengine/ntheory.h, symengine/tests/ntheory/test_ntheory.cpp
=> Mobius function

symengine/functions.cpp, symengine/tests/basic/test_functions.cpp
Do we need to simplify some non trivial forms? Like (4) - (9) [here](http://mathworld.wolfram.com/InverseTrigonometricFunctions.html)
=> [WIP] Some fixes and additions to trig functions

symengine/complex_double.h, symengine/complex_mpc.h, symengine/expression.h, symengine/integer.h, symengine/rational.h, symengine/real_double.h, symengine/real_mpfr.h, symengine/symbol.h
Reason: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Ro-conversion
=> add explicit where possible

bin/test_travis.sh
This script is used by other repos for installation as well and there's no need to run tests on the main repo
=> When TEST_CPP is set to no, disable all tests

benchmarks/series_expansion_sincos_flint.cpp, benchmarks/series_expansion_sincos_piranha.cpp, symengine/series.h, symengine/series_flint.cpp, symengine/series_flint.h, symengine/series_piranha.cpp, symengine/tests/basic/CMakeLists.txt, symengine/tests/basic/test_series.cpp
This includes
- add tests for series interface
- speed up flint sin/cos by 2.5x
- fix: make `SeriesInterface` members public
- fix bugs in `series_flint/piranha.as_basic()`
- remove conditional code in test files
=> further fixes to series

symengine/series.h
The sincos benchmark shows an 8x speedup at N=1000 with this.
=> speed up several Piranha series functions

symengine/series.cpp, symengine/series_flint.h, symengine/series_piranha.cpp, symengine/tests/basic/test_series.cpp
This calls Flint series (if installed) with univariate, else Piranha series (if installed).
=> include Flint series in global series()

symengine/functions.cpp, symengine/functions.h, symengine/tests/basic/test_functions.cpp
```
arcsin				arccos				arctan				arccsc					arcsec					arccot
sin  		x 					sqrt(1-x^2)			x/sqrt(1+x^2)		1/x 					sqrt(1-(1/x)^2)			1/(x*sqrt(1+(1/x)^2))
cos 		sqrt(1-x^2)			x 					1/sqrt(1+x^2)		sqrt(1-(1/x)^2)			1/x 					1/sqrt(1+(1/x)^2)
tan         x/sqrt(1-x^2)		sqrt(1-x^2)/x		x					1/(x*sqrt(1-(1/x)^2))	x*sqrt(1-(1/x)^2)		1/x	
csc 		1/x					1/sqrt(1-x^2)		sqrt(1+x^2)/x		x 						1/sqrt(1-(1/x)^2)		x*sqrt(1+(1/x)^2)
sec 		1/sqrt(1-x^2)		1/x					sqrt(1+x^2)			1/sqrt(1-(1/x)^2)		x  						sqrt(1+(1/x)^2)
cot  		sqrt(1-x^2)/x		x/sqrt(1-x^2)		1/x					x*sqrt(1-(1/x)^2)		1/(x*sqrt(1-(1/x)^2))	x
```
The table used for conversion
=> added more simplifications to trig functions

symengine/printer.cpp, symengine/printer.h, symengine/tests/printing/test_printing.cpp
=> Add ascii art to the main repo

symengine/series_flint.h, symengine/tests/basic/test_series_expansion_URatF.cpp
=> catch all flint aborts with asserts

symengine/series.cpp, symengine/series_visitor.h, symengine/tests/basic/test_series.cpp, symengine/visitor.cpp, symengine/visitor.h
second part of #793, depends on #796
=> series failsafes

symengine/ntheory.cpp, symengine/ntheory.h, symengine/tests/ntheory/test_ntheory.cpp
=> Mertens Function

symengine/functions.cpp, symengine/tests/basic/test_functions.cpp
Fixes #806
@isuruf @Sumith1896
=> Corrected Polygamma function and tests.

symengine/rational.cpp, symengine/tests/basic/test_rational.cpp
@isuruf 
Should the whole if statement be removed ?
=> Bug fix in rational.cpp

symengine/printer.cpp, symengine/real_mpfr.cpp, symengine/tests/basic/test_functions.cpp
This seems to be a bit behind where the other functions are.
=> Gamma function additions

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/tests/cwrapper/test_cwrapper.c
=> Add ascii_art()'s cwrapper

symengine/cwrapper.cpp, symengine/cwrapper.h
Adds the missing documentation as suggested in #781.
=> Documentation of basic_const_set

symengine/mul.cpp, symengine/tests/basic/test_basic.cpp, symengine/tests/basic/test_functions.cpp, symengine/tests/eval/test_eval_arb.cpp
=> Added exception for division by zero

symengine/constants.cpp, symengine/dict.cpp, symengine/dict.h, symengine/expression.cpp, symengine/expression.h, symengine/ntheory.cpp
=> Refactor: hide internal functions and remove unused operator<<

symengine/polynomial.cpp
Also, there's a TODO for implementing horner's scheme for `eval_bit()` which evaluates the function at `2^x`. If that is to be done, I will have to make another recursive function just for this (because of mismatch types). So should I?
=> implemented horners scheme for evaluating polynomials

README.md
=> [ci skip] Add link to Haskell wrappers of SymEngine in README.md

symengine/polynomial.cpp, symengine/tests/basic/test_polynomial.cpp
=> Bug fix in polynomial

symengine/polynomial.cpp
https://github.com/symengine/symengine/pull/865#discussion_r56625981
=> small optimization in eval_bit in univariate_poly

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/tests/cwrapper/test_cwrapper.c
Came up in symengine/SymEngine.jl#17.
=> Get type code of the class from class name

symengine/cwrapper.cpp, symengine/expression.h, symengine/integer.cpp, symengine/integer.h, symengine/polynomial.h, symengine/rational.h, symengine/series_flint.cpp, symengine/series_generic.cpp, symengine/series_piranha.cpp, symengine/tests/basic/test_number.cpp, symengine/tests/eval/test_eval_mpfr.cpp
@CodeMaxx, can you check and review?
=> Fix Clang warnings

symengine/add.cpp, symengine/add.h, symengine/mul.cpp, symengine/mul.h, symengine/tests/basic/test_arit.cpp
Addresses #885 
Along with *Method to add a vector of basic together*, I extended it to `mul` also. 
Ping @abinashmeher999 @isuruf
=> Added add and mul of vec_basic

symengine/dict.cpp, symengine/tests/basic/test_basic.cpp
Added tests for better coverage.
changed `*_eq` (* as wildcard) function (readability)
=> Added tests for dict

symengine/CMakeLists.txt, symengine/dense_matrix.cpp, symengine/derivative.cpp, symengine/derivative.h, symengine/matrix.h, symengine/sparse_matrix.cpp, symengine/tests/basic/test_basic.cpp, symengine/tests/matrix/test_matrix.cpp
=> Matrix improvements

symengine/functions.cpp, symengine/functions.h, symengine/numer_denom.cpp, symengine/tests/basic/test_functions.cpp
Fixes symengine/symengine.py#57
Fixes symengine/symengine#871
=> Improve could_extract_minus and handle_minus

symengine/functions.cpp
=> small bug fix in lambertw is_canonical, leftover from #854

symengine/basic-inl.h, symengine/basic.h, symengine/functions.cpp, symengine/functions.h, symengine/pow.cpp, symengine/pow.h
3 classes,
`OneArgFunction`
`TwoArgFunction`
`MultiArgFunction`
are introduced to avoid code duplication. (Let me know if you have better suggestions for the name)
=> Refactor functions

symengine/dict.cpp, symengine/dict.h, symengine/polynomial.cpp, symengine/tests/basic/test_basic.cpp
Removing few redundancies and other misc changes.
=> [WIP] some modifictions in dict.cpp functions

codecov.yml
Codecov recently stopped changing settings in their UI
=> Add a codecov.yml

benchmarks/series.cpp
=> Fix benchmark of series

.mailmap, AUTHORS
Added Pradyot, Nishant, malayaleecoder, Zhang, Zheng, Charles, Kunal, Rajith, Matthew, Iris, and James to AUTHORS. Welcome to SymEngine !
@pradyotprakash, @nishnik, @malayaleecoder, @codeworm96, @htfy96, @chenchfort, @kunal-iitkgp, @rajithv, @myluszczak, @irislq, @StoicBronco let me know if there needs to be any changes.
=> [skip ci] Update AUTHORS

.clang-format, symengine/cwrapper.cpp, symengine/cwrapper.h
@rajithv, @abinashmeher999, can you review?
=> cwrapper : add const where appropriate

benchmarks/symbench.cpp, benchmarks/symbench.m
=> symbench benchmark

.travis.yml, CMakeLists.txt, README.md, symengine/mp_wrapper.cpp
=> Use gmp as integer_class by default

symengine/fields.cpp, symengine/fields.h, symengine/tests/basic/test_fields.cpp
Zassenhaus's Distinct degree factorization.
=> Distinct degree

symengine/dense_matrix.cpp, symengine/derivative.cpp, symengine/subs.h, symengine/tests/basic/test_subs.cpp
=> SymPy subs

symengine/dense_matrix.cpp, symengine/diophantine.cpp, symengine/matrix.h, symengine/tests/matrix/test_matrix.cpp
=> pivoted LU and API changes

symengine/expand.cpp, symengine/polys/uintpoly.cpp, symengine/polys/uintpoly.h, symengine/polys/upolybase.h
move `pow_upoly` to upolybase (so that `UExprPoly` can also use it) and make expand use `pow_upoly` instead of it's own implementation.
=> pow_upoly changes

.mailmap, AUTHORS
@parsoyaarihant, let me know if your name and email are correct.
=> Add Arihant to AUTHORS.

symengine/derivative.cpp, symengine/functions.cpp, symengine/series.cpp, symengine/series_visitor.h, symengine/symengine_rcp.h, symengine/tests/basic/test_basic.cpp, symengine/tests/basic/test_series_generic.cpp, symengine/visitor.cpp, symengine/visitor.h
Added a few fixes on top of #1014.
=> has_symbol(): replace unnecessary RCP function arg

symengine/tests/basic/test_series_generic.cpp
gives a 5.5x speedup in `test_series_generic`.
=> reduce precision in many series_generic tests; part of #1012

symengine/tests/basic/test_basic.cpp, symengine/visitor.cpp, symengine/visitor.h
cleaned up and updated version of #1006.
=> coeff(): replace unnecessary RCP function args

symengine/flint_wrapper.h, symengine/mp_wrapper.h
=> add canonicalize to mpq_wrapper and fmpq_wrapper ctor from two integers

symengine/printer.cpp, symengine/printer.h, symengine/tests/cwrapper/test_cwrapper.c, symengine/tests/printing/test_printing.cpp
1. Fixed an issue with RealDouble
2. `sqrt(2)` is printed as `sqrt(2)` instead of `2**(1/2)`
=> Fix some printing issues

symengine/fields.cpp, symengine/fields.h, symengine/tests/basic/test_fields.cpp
This PR includes the methods to factor any polynomial in finite field.
Currently it uses `Zassenhaus's` algorithm. As `Shoup's` algorithm get implemented, will change `gf_factor` accordingly.
=> Factorization in Fields

symengine/fields.cpp, symengine/fields.h, symengine/tests/basic/test_fields.cpp
It is faster than Zassenhaus's when `modulo_` is large.
=> Shoup's algorithm for Factorization in finite field

.gitignore, CMakeLists.txt, cmake/cotire.cmake, symengine/CMakeLists.txt
with a cmake option `WITH_COTIRE`
=> add cotire to speed up builds

symengine/CMakeLists.txt, symengine/codegen.h, symengine/tests/printing/CMakeLists.txt, symengine/tests/printing/test_ccode.cpp
Minimum codegen needed for pycalphad.
cc @certik, @richardotis, @asmeurer
=> C Code generation

symengine/fields.cpp, symengine/fields.h, symengine/tests/basic/test_fields.cpp
It lets us create `GaloisField` poly from `UIntPoly`.
=> Added method GaloisField::from_uintpoly

symengine/derivative.cpp, symengine/fields.cpp, symengine/fields.h, symengine/tests/basic/test_fields.cpp
This PR implements `diff` method for `GaloisField` objects.
And moves some function definition from `.h` to `.cpp`
=> diff method

appveyor.yml
Workaround until appveyor/ci#996 is resolved
=> Fix version mismatch of gcc and libstdc++ in appveyor

symengine/polys/basic_conversions.cpp, symengine/polys/basic_conversions.h, symengine/polys/msymenginepoly.cpp, symengine/polys/msymenginepoly.h, symengine/tests/basic/test_parser.cpp, symengine/tests/polynomial/test_basic_conversions.cpp
=> Basic to mpoly

symengine/infinity.cpp, symengine/tests/basic/test_infinity.cpp
Added `Infty::div` with testcases. @isuruf
=> Added Infinity division

symengine/logic.cpp, symengine/logic.h, symengine/tests/logic/test_logic.cpp
I have added NOR Logic.
Can you please review and suggest improvements.
=> Added NOR Logic.

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/tests/cwrapper/test_cwrapper.c
Fixes: #1143 
Though the code works (locally), I am still not confident of my implementation. A review would be really helpful.
Edit: Some of the builds are indeed raising issues of SegFault, hence there is a need for improvement.
=> Fix for Issue #1143 (Wrapped as_numer_denom() in C)

CMakeLists.txt, bin/test_travis.sh
=> Added -ftrapv Flag for Issue #737 + Minor Grammatical Fix

symengine/complex.h
renamed conjugate to modulus_sq.
Please review this and suggest if this change is necessary @isuruf @certik
=> edit a misleading variable name

symengine/derivative.cpp, symengine/functions.cpp, symengine/functions.h, symengine/tests/basic/test_functions.cpp
Relevant: #814 
Please review and suggest improvements.
=> Implemented LeviCivita Derivative and Added Test

symengine/add.cpp, symengine/cwrapper.cpp, symengine/derivative.cpp, symengine/diophantine.cpp, symengine/expand.cpp, symengine/functions.cpp, symengine/mul.cpp, symengine/ntheory.cpp, symengine/polys/basic_conversions.cpp, symengine/polys/basic_conversions.h, symengine/pow.cpp, symengine/rings.cpp, symengine/subs.h, symengine/tests/basic/test_arit.cpp, symengine/tests/basic/test_functions.cpp, symengine/tests/basic/test_series.cpp, symengine/tests/eval/test_eval_arb.cpp, symengine/tests/eval/test_evalf.cpp, symengine/tests/printing/test_ccode.cpp
=> Replaced `rcp_static_cast<>()->` with `down_cast<>().`

.mailmap, AUTHORS
@jppelteret and @ranjithkumar007, please let me know if there is any error.
=> [skip ci] Add Jean-Paul and Ranjith to AUTHORS. Welcome to SymEngine!

symengine/complex.cpp, symengine/complex.h, symengine/complex_double.h, symengine/complex_mpc.h, symengine/functions.cpp, symengine/infinity.cpp, symengine/infinity.h, symengine/integer.h, symengine/number.h, symengine/rational.h, symengine/real_double.h, symengine/real_mpfr.h, symengine/series.h, symengine/tests/basic/test_number.cpp
Relevant: #915 
@isuruf The ComplexBase is currently an empty shell. What more functionality is expected to be implemented?
=> Class ComplexBase and is_a_Complex() and is_complex() Function

symengine/functions.cpp, symengine/pow.cpp
As EvaluateInfty Class is introduced ..we don't need any additional checks for +/-inf in is_canonical().
=> remove outdated comments

symengine/functions.cpp, symengine/tests/basic/test_functions.cpp
=> Fix handling of minus in abs, sinh, cosh, ... etc

README.md
Fixes #1140 
Added in https://github.com/Homebrew/homebrew-science/pull/4842.
Can somebody check in OS X that this works? I only checked in Linux using linuxbrew and don't have access to OS X.
=> [skip ci] Add homebrew instructions

symengine/constants.cpp, symengine/constants.h, symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/eval_arb.cpp, symengine/eval_double.cpp, symengine/eval_mpc.cpp, symengine/eval_mpfr.cpp, symengine/lambda_double.h, symengine/llvm_double.h, symengine/parser.cpp, symengine/tests/cwrapper/test_cwrapper.c, symengine/tests/eval/test_eval_double.cpp, symengine/tests/eval/test_eval_mpc.cpp, symengine/tests/eval/test_eval_mpfr.cpp
=> add Symbolic constants

symengine/functions.cpp, symengine/tests/basic/test_functions.cpp
[formula ref ](http://dlmf.nist.gov/8.8)
=> bug fix in upper and lower gamma

symengine/derivative.cpp, symengine/functions.cpp, symengine/functions.h, symengine/mul.cpp, symengine/tests/basic/test_functions.cpp
Relevant: #814 
A workaround has been implemented as of now (for derivation with respect to 's'). Please suggest improvements.
=> Incorporated Zeta, UpperGamma and LowerGamma Derivative and Added Tests

symengine/functions.cpp, symengine/functions.h, symengine/tests/basic/test_functions.cpp
=> implement digamma,trigamma using polygamma

symengine/pow.cpp, symengine/tests/basic/test_arit.cpp
Fixes https://github.com/symengine/symengine.py/issues/135
=> Fix pow(x, 0)

symengine/dense_matrix.cpp, symengine/tests/matrix/test_matrix.cpp
@certik @isuruf I would be requiring some clarification for the second part of the issue. Please check my comment: https://github.com/symengine/symengine/issues/1025#issuecomment-265145254
=> Restructured mul_dense_dense() function

symengine/subs.h, symengine/tests/basic/test_subs.cpp
Fixes https://github.com/symengine/symengine/issues/1209
=> Allow substituting arg in derivative

.travis.yml, bin/travis_clang.sh
possible fix for #1238 , going by the idea of a dedicated travis test for checking formatting as suggested by @certik in the issue.
Fixes #1238
=> Make formatting test fail more clear

symengine/llvm_double.h, symengine/tests/eval/test_lambda_double.cpp
=> Add support for log in LLVMDoubleVisitor

symengine/CMakeLists.txt, symengine/llvm_double.cpp, symengine/llvm_double.h, symengine/tests/eval/test_lambda_double.cpp
=> Move llvm_double.h implementation to a cpp file and add more functions

CMakeLists.txt
Added missing LLVM components `asmparser` and `nativecodegen`
=> Add further required LLVM components to CMakeLists.txt

symengine/eval_arb.cpp, symengine/tests/eval/test_eval_arb.cpp
This PR is basically a rebase to master + additional minor changes to #861 by @saroad.
As always, please review and suggest improvements.
=> Implemented a few methods in symengine/eval_arb.cpp

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/printer.cpp, symengine/printer.h, symengine/tests/cwrapper/test_cwrapper.c
=> Julia printer

.mailmap, AUTHORS
@kvmanohar22, @kanchanarp, @saroad, let me know if your names are correct.
=> [skip ci] Add Kv, Kanchana and Melanka to AUTHORS. Welcome to SymEngine!

symengine/printer.cpp, symengine/printer.h, symengine/tests/cwrapper/test_cwrapper.c
fixes #1257 
I am not quite sure of this, Can you have a look @isuruf @ChrisRackauckas?
=> JuliaStrPrinter for nan and infs

symengine/dense_matrix.cpp, symengine/matrix.h, symengine/tests/matrix/test_matrix.cpp
As always, please review and suggest improvements.
=> Additional Functionalities for DenseMatrix

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/tests/cwrapper/test_cwrapper.c
Added `dense_matrix_{ diff, jacobian }` for elementwise differentiation and jacobian of a dense matrix.
=> Added C wrappers for dense matrix differentiation

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/tests/cwrapper/test_cwrapper.c
Added `setbasic_erase` to C wrappers.
=> Added setbasic_erase to C wrappers

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/tests/cwrapper/test_cwrapper.c
Ok, I finally managed to make this PR. Is everything Ok?
If yes, what about having `number_is_negative`, `number_is_positive`, `number_is_complex`?
I could try to do that as well.
Fixes #1254
=> Introduction of number_is_zero in C wrappers

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/tests/cwrapper/test_cwrapper.c
added `dense_matrix_row_join`, `dense_matrix_col_join`
=> Added C wrappers for row_join, col_join

.travis.yml, bin/install_travis.sh, bin/test_travis.sh
=> Use ccache and cache miniconda installation

symengine/symbol.cpp, symengine/symbol.h, symengine/tests/basic/test_functions.cpp, symengine/tests/logic/test_logic.cpp, symengine/type_codes.inc
=> Implemented Dummy Class

symengine/dense_matrix.cpp, symengine/matrix.h, symengine/tests/matrix/test_matrix.cpp
Relevant: https://github.com/symengine/symengine.py/issues/17
Currently implementing `norm` is out of scope as for that we need to have a method for finding eigenvalues, which is planned to be implemented as a part of Ranjith's project.
=> Implemented dot() and cross() methods

symengine/functions.cpp, symengine/tests/basic/test_functions.cpp, symengine/tests/printing/test_printing.cpp
As suggested by @isuruf in #1290.
=> Simplification for Add objects in Floor and Ceiling

symengine/symbol.cpp, symengine/tests/basic/test_functions.cpp
=> fix bug in dummy::compare

symengine/CMakeLists.txt, symengine/utilities/teuchos/CMakeLists.txt
=> Use GNUInstallDirs.cmake for figuring out the BINDIR and LIBDIR

bin/install_travis.sh
=> [skip appveyor] update brew

symengine/cwrapper.h
It seems that these two comments are not valid anymore.
=> Fix comments

symengine/parser.cpp, symengine/tests/basic/test_parser.cpp
i really think we need to shift to an autogenerated parser. this is getting out of hands. took me way too much time to read my own code :(
=> parser: unary operator fixing

symengine/printer.cpp, symengine/printer.h, symengine/tests/printing/test_printing.cpp
=> Add Xor to printing and test it

symengine/dense_matrix.cpp, symengine/matrix.h, symengine/tests/matrix/test_matrix.cpp
=> use inverse_pivoted_LU

symengine/numer_denom.cpp, symengine/tests/basic/test_as_numer_denom.cpp
Fixes https://github.com/symengine/symengine/issues/1327
=> Fix as_numer_denom cancellation bug

symengine/as_real_imag.cpp, symengine/tests/basic/test_as_real_imag.cpp
Fixes #1381 
Should I add more tests?
=> Added Abs to as_real_imag

symengine/tests/matrix/test_matrix.cpp, symengine/visitor.cpp, symengine/visitor.h
=> Added free_symbols for matrices

symengine/llvm_double.cpp, symengine/llvm_double.h, symengine/tests/eval/test_lambda_double.cpp
=> Save and load LLVM compiled functions

symengine/codegen.h, symengine/tests/printing/test_ccode.cpp
#1380 
@bjodah @isuruf @ShikharJ
=> Make ccode print exp(x)

symengine/basic.h, symengine/dict.h, symengine/visitor.cpp
=> Added is present check to FreeSymbolsVisitor

.mailmap, AUTHORS
@Marlin-Na, @Wrzlprmft, @npochhi, @eeshan9815, thanks for your contributions. I've added you to the authors list. Let me know if you want to change your name or email address.
=> Add Marlin, Gerrit, Nilay and Eeshan to AUTHORS. Welcome to SymEngine!

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/tests/basic/test_basic.cpp, symengine/tests/cwrapper/test_cwrapper.c, symengine/visitor.cpp, symengine/visitor.h
Extend CoeffVisitor for function symbols
Add cwrapper function basic_coeff
=> Get coefficients for function symbols

symengine/CMakeLists.txt
=> Sort the cpp file list in CMakeLists.txt

symengine/parser.cpp, symengine/tests/basic/test_parser.cpp
=> Fix parsing

.travis.yml, bin/test_travis.sh, symengine/sparse_matrix.cpp
=> Build using _GLIBCXX_DEBUG for 1 Travis job

symengine/functions.cpp, symengine/tests/basic/test_functions.cpp
=> Fix trig for a - b * pi

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/tests/basic/test_basic.cpp, symengine/tests/cwrapper/test_cwrapper.c, symengine/visitor.cpp, symengine/visitor.h
Providing a function `function_symbols` for collecting all `FunctionSymbol` objects in an expression.
=> Collecting function symbols in an expression

codecov.yml
Let's see if this fixes the coverage.
cc @bjodah, @certik
=> Ignore benchmarks in codecov

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/tests/cwrapper/test_cwrapper.c
=> Wrap atan2

.travis.yml, bin/install_travis.sh, bin/test_travis.sh, bin/travis_clang_format.sh, symengine/tests/eval/test_lambda_double.cpp
The commits in #1471 was a mess and rebasing was just a mess so adding the diff as a single commit here.
=> Use clang++-7 with Asan & UBsan on Travis

CMakeLists.txt, symengine/CMakeLists.txt
Fixes https://github.com/symengine/symengine/issues/1473
=> Use exclude-libs

symengine/mul.cpp, symengine/pow.cpp, symengine/tests/basic/test_basic.cpp
and fix some is_canonical errors in https://github.com/symengine/symengine.py/issues/256
Fixes https://github.com/symengine/symengine.py/issues/256
cc @Melisius, @certik
=> Fix segfault in differentiation

symengine/numer_denom.cpp, symengine/tests/basic/test_as_numer_denom.cpp
Fix https://github.com/symengine/symengine/issues/1426
=> Remove recursively calling as_numer_denom on itself

symengine/CMakeLists.txt, symengine/latex.cpp, symengine/latex.h, symengine/printer.cpp, symengine/printer.h, symengine/sets.cpp, symengine/sets.h, symengine/tests/printing/test_printing.cpp
=> Added initial Latex functions

symengine/cwrapper.cpp, symengine/eval.cpp, symengine/eval.h, symengine/tests/eval/test_evalf.cpp
Fixes https://github.com/symengine/symengine/issues/1488
=> Support symbols in evalf

AUTHORS
Welcome to SymEngine!
@clouds56, @ahumenberger, @KKaempen, @SylvainCorlay, @ladrift, can you please let us know if you want to change your name or email address here?
=> Add Ziyi, Andreas, Kieran, Clouds, Sylvain and Alan to AUTHORS.

README.md
Fixed Some Grammatical Mistakes in README.md
=> Fixed Some Typographical Error in README.md

notebooks/symengine.ipynb, symengine/expression.h, symengine/printers.h, symengine/printers/latex.cpp, symengine/tests/printing/test_printing.cpp
Fixes https://github.com/symengine/symengine/issues/1510
=> rendering on jupyter xeus-cling kernel

symengine/lambda_double.h, symengine/llvm_double.cpp, symengine/llvm_double.h, symengine/tests/eval/test_lambda_double.cpp
This is regarding #1521.
I think i've managed floor and ceiling. Not sure about sign and atan2, seems like they are not supported by llvm?
=> added llvm support for floor and ceiling

bin/test_travis.sh, symengine/llvm_double.cpp, symengine/llvm_double.h, symengine/tests/eval/test_lambda_double.cpp
Fixes https://github.com/symengine/symengine/issues/1525
=> Fixes memleak in LLVMDoubleVisitor

symengine/eval_double.cpp, symengine/lambda_double.h, symengine/subs.h, symengine/tests/eval/test_eval_double.cpp
Also add substitution of conditionals for Piecewise functions
=> Evaluate Piecewise functions and booleans using eval_double()

symengine/derivative.cpp, symengine/tests/basic/test_basic.cpp
Fixes https://github.com/symengine/symengine/issues/1533
=> Create canonical Add in diff of Mul

README.md
These are outdated and not maintained
=> [skip ci] [ci skip] Remove Ubuntu and Homebrew from README

.mailmap, AUTHORS
@bocklund, let me know if the email and name are correct.
=> Add Brandon to authors. Welcome to SymEngine!!

symengine/functions.cpp, symengine/tests/basic/test_functions.cpp
As discussed on gitter with @isuruf (I was @torshind_gitlab).
=> Simplify abs(abs(x))

symengine/cwrapper.cpp, symengine/cwrapper.h
Related: https://github.com/symengine/symengine.R/issues/47
=> Add mathml, latex, ccode, jscode to cwrapper

CMakeLists.txt, README.md
Fixes https://github.com/symengine/symengine/issues/1542
=> Remove -march=native and add a note to README

symengine/cwrapper.h
According to:
- https://github.com/symengine/SymEngine.jl/blob/master/src/ctypes.jl#L181
- https://github.com/symengine/SymEngine.jl/blob/master/src/types.jl#L109
- https://github.com/symengine/SymEngine.jl/blob/master/src/types.jl#L270
=> Add comments that caller should be responsible to free the string

.mailmap, AUTHORS
@mydatamodels, let me know if you want to change the name or email.
=> [skip ci] [ci skip] Add Marcello to AUTHORS. Welcome to SymEngine !!

cmake/UserOverride.cmake
https://github.com/symengine/symengine/pull/1577 was accidentally closed.
=> Remove -march=native in UserOverride.cmake

symengine/CMakeLists.txt
We do the same in linux and osx for shared libraries
=> Version the dll

benchmarks/CMakeLists.txt, benchmarks/diff_cache.cpp, symengine/basic.h, symengine/dense_matrix.cpp, symengine/derivative.cpp, symengine/derivative.h, symengine/expression.h, symengine/matrix.h, symengine/sparse_matrix.cpp, symengine/subs.h
This reverts commit 297a403fd51b1d366cdedde348799a7a69271bda.
=> Don't revisit in diff

symengine/subs.h, symengine/tests/basic/test_subs.cpp
This caches intermediate results for performance
=> Don't revisit in subs

symengine/dense_matrix.cpp, symengine/matrix.h, symengine/sparse_matrix.cpp, symengine/tests/matrix/test_matrix.cpp
It looks like QR and Cholesky are ready to be put on the same footing as the LU-type factorizations.
=> Cleanup matrix factorizations

symengine/llvm_double.cpp, symengine/llvm_double.h, symengine/tests/eval/test_lambda_double.cpp
This is just the test for https://github.com/symengine/symengine/pull/1614.
=> added test for LLVMDouble with different values for opt_level

symengine/printers/strprinter.cpp, symengine/printers/strprinter.h, symengine/tests/printing/test_printing.cpp
fix https://github.com/symengine/SymEngine.jl/issues/178
=> add complex number printing specialization for julia

symengine/CMakeLists.txt, symengine/polys/cancel.h, symengine/tests/polynomial/CMakeLists.txt, symengine/tests/polynomial/test_cancel.cpp
In this Pull request a function **cancel** will be implemented for univariate polynomial.
Input and Output API currently is like
```
void cancel(const RCP<const Basic> &self, const RCP<const Basic> &other,
const Ptr<RCP<const UIntPolyFlint>> &result_self, const Ptr<RCP<const UIntPolyFlint>> &result_other)
```
Main work is done in the PR #1620 Please go through this PR.
CC @certik @isuruf
=> Implement cancel method for polynomial

LICENSE
=> Update license for bison parser

LICENSE
See https://github.com/symengine/symengine/blob/master/cmake/cotire.cmake
=> Add license for cmake/cotire.cmake

CMakeLists.txt, symengine/CMakeLists.txt
Fixes https://github.com/symengine/symengine.py/issues/306
=> Hide LLVM symbols in OSX too

symengine/sets.cpp, symengine/tests/basic/test_sets.cpp
=> Fix union of FiniteSet containing symbols and Interval (Fixes #1648)

CMakeLists.txt, symengine/CMakeLists.txt
And also use `CMAKE_CXX_FLAGS` where appropriate.
=> Drop WITH_CPP14 flag

CMakeLists.txt, symengine/add.cpp, symengine/functions.h, symengine/logic.h, symengine/solve.cpp, symengine/visitor.h
Can't build yet, but these changes can be merged for now.
cc @Marlin-Na
=> Partial support for Oracle Development Studiio

symengine/eval_double.cpp, symengine/tests/basic/test_parser.cpp
=> use std:: instead of ::

symengine/basic-inl.h, symengine/basic.h, symengine/cwrapper.cpp
@Marlin-Na, this should reduce some of the warnings.
Let me know if you encounter other warnings and we can fix them.
=> Fix a warning on ILP64 systems

symengine/cwrapper.cpp, symengine/polys/basic_conversions.h, symengine/tests/cwrapper/test_cwrapper.c
=> Fix return value of basic_solve_poly

benchmarks/CMakeLists.txt, benchmarks/bench_eval_double.cpp, benchmarks/bench_lambda_double.cpp
- add `bench_lambda_double` to benchmark LambdaRealDoubleVisitor
- fix segfault in `bench_eval_double`
=> add LambdaRealDoubleVisitor benchmark

symengine/dense_matrix.cpp, symengine/mul.cpp, symengine/number.h, symengine/pow.cpp, symengine/sparse_matrix.cpp, symengine/tests/matrix/test_matrix.cpp
Fixes https://github.com/symengine/symengine/issues/1681
cc @rhklite
=> Fix checking for float zero in matrix operations

symengine/basic-inl.h, symengine/basic.h, symengine/dense_matrix.cpp, symengine/matrix.h, symengine/number.h, symengine/test_visitors.cpp, symengine/test_visitors.h, symengine/tests/basic/test_basic.cpp, symengine/tests/basic/test_test_visitors.cpp, symengine/tests/matrix/test_matrix.cpp
Add methods `is_zero`, `is_real`, `is_diagonal`, `is_symmetric` and `is_hermitian` to `DenseMatrix`.
This PR depends on #1702.
=> Add test methods for zero, real, diagonal, symmetric and hermitian matrices

symengine/dense_matrix.cpp, symengine/matrix.h, symengine/tests/matrix/test_matrix.cpp
Add member function to calculate the trace for `DenseMatrix`
=> Add trace for DenseMatrix

symengine/polys/uintpoly_flint.h
Should fix (?) [the error](https://github.com/symengine/symengine.py/issues/340) with `symengine.py`
=> flint: Heed -Werror=pessimizing-move

docs/Doxygen/md/doc_guide.md
----
This PR is part of the **Google Season of Docs 2020**
=> Doxygen style guide

symengine/add.cpp, symengine/add.h, symengine/basic.cpp, symengine/basic.h
As per the style guide, after #1726 and #1727 
----
This PR is part of the **Google Season of Docs 2020**
=> API Documentation

CMakeLists.txt, cmake/SymEngineConfig.cmake.in, symengine/lambda_double.h
=> Fix a segfault in lambda_double.h

.mailmap, AUTHORS
@rikardn, @myd7349, @HaoZeke, @sudoWin, @Marlin-Na, @willsimmons1465, @f-koehler, let me know whether your preferred name and email is in the AUTHORS file and if not I'll change it.
=> Add Anubhav, Rikard, Will, myd7340, Fabian, Rohit to AUTHORS.

symengine/test_visitors.cpp, symengine/test_visitors.h, symengine/tests/basic/test_test_visitors.cpp
Implemented using a visitor. Instead of calling `free_symbols` as sympy does it operates in two modes. One where only symbols are considered. This makes early returns possible and will make it faster. All unit tests from sympy have been incorporated.
=> Add is_polynomial function

.github/workflows/ci.yml, CMakeLists.txt, appveyor.yml, bin/test_symengine_unix.sh, bin/test_travis.sh
- move msys ci jobs from appveyor to github actions
- change order of `LIBS` in CMakeLists.txt: ensure gmp comes after mpc/mpfr to resolve linker errors in msys
=> move msys builds from appveyor to github actions

symengine/dense_matrix.cpp, symengine/matrix.h, symengine/tests/basic/test_solve.cpp
A unit test for testing solve related to issue 1745 where solve returns  a nan.
=> A unit test for  issue 1745. 

symengine/assumptions.cpp, symengine/assumptions.h, symengine/number.h, symengine/test_visitors.cpp, symengine/test_visitors.h, symengine/tests/basic/test_test_visitors.cpp
Adding `is_complex` test. This is a bit more complete than the previous test functions. It tests for singular points for most trigonometric functions, supports assumptions and `add`, `mul` and `pow`.
=> Add is_complex

symengine/dense_matrix.cpp, symengine/matrix.h, symengine/tests/matrix/test_matrix.cpp
=> Use assumptions in matrix is_real

symengine/number.h, symengine/test_visitors.cpp, symengine/test_visitors.h, symengine/tests/basic/test_test_visitors.cpp
=> Add is_integer

symengine/basic.h, symengine/rewrite.cpp, symengine/test_visitors.h, symengine/tests/basic/test_functions.cpp, symengine/tests/basic/test_test_visitors.cpp
=> Add rewrite_as_sin

symengine/number.h, symengine/test_visitors.cpp, symengine/test_visitors.h, symengine/tests/basic/test_test_visitors.cpp
Add the `is_nonzero` function. Reusing the `ZeroVisitor`
=> Add is_nonzero

symengine/subs.h, symengine/tests/basic/test_subs.cpp
fixes https://github.com/symengine/symengine/issues/1794
=> added logical operators to subs

symengine/CMakeLists.txt, symengine/printers.h, symengine/printers/stringbox.cpp, symengine/printers/stringbox.h, symengine/printers/unicode.cpp, symengine/printers/unicode.h, symengine/tests/printing/test_printing.cpp
=> Add unicode printer

symengine/mp_boost.cpp
=> use list initialization for int parameter since type depends on boost version

.github/workflows/ci.yml, bin/test_travis.sh
Trying to get msan to work (as an alternative to #1820)
=> Ubuntu 20.04 for msan & ubsan tests (llvm-12)

symengine/test_visitors.cpp, symengine/test_visitors.h, symengine/tests/basic/test_test_visitors.cpp
Basic check for all terms positive or all terms negative in `Add` for `is_positive`
=> Support Add by is_positive

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/tests/cwrapper/test_cwrapper.c
Fixes https://github.com/symengine/symengine/issues/1827
=> wrap add(vector) in C

.mailmap, AUTHORS
cc @naveensaigit, @cqc-alec @HQS-Peter @tbb300 
Let me know if you want to change your name or email address here.
Thanks for your contributions.
=> [skip ci] [ci skip] Add Naveen, Alec, Peter and Tom to AUTHORS. Welcome to SymEngine!!

symengine/ntheory.cpp, symengine/ntheory.h, symengine/ntheory_funcs.cpp, symengine/ntheory_funcs.h, symengine/tests/ntheory/test_ntheory_funcs.cpp
Mathematica has PolygonalNumber: https://reference.wolfram.com/language/ref/PolygonalNumber.html
The polygonal root is the inverse: http://oeis.org/wiki/Polygonal_numbers#Polygonal_roots
=> Add polygonal numbers and polygonal roots functions

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/tests/cwrapper/test_cwrapper.c
=> Add ceiling and floor to cwrapper

symengine/refine.cpp, symengine/refine.h, symengine/tests/basic/test_refine.cpp
log(x**y) -> x*log(y) if x > 0 and y real.
=> Add logarithm power rule to refine

symengine/ntheory.cpp, symengine/ntheory.h, symengine/tests/ntheory/test_ntheory.cpp
Add number theoretic function `mp_perfect_power_decomopsition`. Analogous to `perfect_power` in sympy.
=> Add function to decompose perfect powers

symengine/refine.cpp, symengine/tests/basic/test_refine.cpp
For example:
`log(8) = 3*log(2)`
Also
`log(4) / 2 = log(2)`
=> Refine log of integers which are perfect powers

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/tests/cwrapper/test_cwrapper.c
=> Dumps and loads added in C wrapper

.mailmap, AUTHORS
@PerformanceCoder @eendebakpt @HaoZeke let me know if your name and email address are correct.
=> Add Pieter and Zgoda to SymEngine AUTHORS file

symengine/mul.cpp, symengine/pow.cpp, symengine/tests/basic/test_subs.cpp, symengine/utilities/matchpycpp/environment.yml
=> Fix Mul canonical to match that of Pow canonical

symengine/subs.h, symengine/tests/basic/test_subs.cpp
Fixes https://github.com/symengine/symengine/issues/1912
=> Fix substituting I

symengine/mul.cpp, symengine/tests/basic/test_basic.cpp
Fixes https://github.com/symengine/symengine.py/issues/407
=> Fix (-x)**I

symengine/matrix.h, symengine/sparse_matrix.cpp, symengine/tests/matrix/test_matrix.cpp
And create a virtual method in `Matrix` base class.
=> Add is_real to CSRMatrix

symengine/basic-inl.h, symengine/basic.h, symengine/test_visitors.cpp, symengine/test_visitors.h, symengine/tests/basic/test_test_visitors.cpp
* Support `Mul` and `Pow` in `is_real`
* Fix flawed `Add` in `is_real`
Fix #1922
=> Support Mul and Pow in is_real

symengine/parser/parser.cpp, symengine/tests/basic/test_parser.cpp
Fixes https://github.com/symengine/symengine.py/issues/419
=> Add sympy names for Eq, Lt, etc and check before casting

.mailmap, AUTHORS
@thesamesam, let me know if your email and name are correct.
@PerformanceCoder, fixed now. Can you check if it's correct?
=> Add Sam to AUTHORS and update emails

CONTRIBUTING.md
for whatever reason the Style Guide doesn't link to the style guide - so I'm suggesting an absolute http path
=> Adding a Correct Path to the Style Guide

symengine/complex_double.cpp, symengine/complex_double.h, symengine/subs.h, symengine/tests/basic/test_subs.cpp
Also fixes https://github.com/symengine/symengine/issues/1961
=> In subs, check if coeff is a number and use a faster code path

binder/doxygendoc.yml
For proper rendering of the documentation. See https://github.com/HaoZeke/doxyYoda/issues/1 for more details.
=> MAINT: Pin doxygen

bin/install_travis.sh, symengine/flint_wrapper.h
Fixes https://github.com/symengine/symengine/issues/1983
=> Fix flint headers and replace use of deprecated funcs in flint2/3

symengine/rational.cpp, symengine/tests/basic/test_arit.cpp
Fixes https://github.com/symengine/symengine.py/issues/460 as well
=>  Fix (negative_integer)**rational

symengine/cwrapper.cpp, symengine/cwrapper.h, symengine/tests/cwrapper/test_cwrapper.c
=> Adding support for basic_as_two_terms

symengine/tests/cwrapper/test_cwrapper.c
Fixes https://github.com/symengine/symengine/issues/2040
=> Fix as_numer_denom test

symengine/printers/latex.cpp, symengine/tests/printing/test_printing.cpp
Fixes https://github.com/symengine/symengine/issues/2058
=> Fix latex printing for abs and variables with _

symengine/basic-inl.h, symengine/constants.cpp, symengine/constants.h, symengine/derivative.cpp, symengine/functions.cpp, symengine/logic.cpp, symengine/logic.h, symengine/tests/basic/test_integer.cpp
Fixes https://github.com/symengine/symengine/issues/2057
=> Use nifty counter idiom for SIOF

symengine/cwrapper.cpp, symengine/printers/unicode.cpp, symengine/tests/basic/test_as_numer_denom.cpp, symengine/tests/basic/test_as_real_imag.cpp
Fix symbols conflicts to allow compilation with CMAKE_UNITY_BUILD=ON
=> Add support for UNITY_BUILD

symengine/cwrapper.h
Fixes https://github.com/symengine/symengine/issues/1599
=> allow C wrapper to be used from C++

.github/workflows/ci.yml
=> CI: ubuntu-20.04 is deprecated

.github/workflows/ci.yml, bin/test_symengine.sh, symengine/tests/basic/test_functions.cpp
Currently we have CI jobs for the sanitizers:
- address
- undefined
- memory
This PR adds a config with:
- thread
https://github.com/google/sanitizers/wiki/threadsanitizercppmanual
=> CI-config for tsan

symengine/tests/basic/test_as_numer_denom.cpp, symengine/tests/basic/test_basic.cpp, symengine/visitor.cpp, symengine/visitor.h
=> Add HasBasicVisitor and has_basic(...)
