src/cwrapper.cpp
src/cwrapper.h
src/tests/cwrapper/test_cwrapper.c

This doesn't use any heap allocation, and it looks to me that a program in C should be as fast as an equivalent program in C++ now.
There are still things that need to be polished, for example I would like to get rid of declaring the `RCP<const Basic> *s2 = RCP_cast(s);` and just use `RCP_cast(s)` directly, but the compiler complains.
The `SIZE_OF_RCP_BASIC` thing is also not ideal, but we can't use `sizeof(RCP<const Basic>)` in the C header file, so I don't know how to do it any other way.
/cc @isuruf, @fredrik-johansson

Use placement new in the C wrapper

---

src/pow.cpp
src/tests/printing/test_printing.cpp

printing: fix to the missing parentheses issue #380
Example:
```
In[1]: (Integer(3)/2)**(Integer(1)/2)
```
Before fix-`Out[1]: 3/2^(1/2)`
After fix-`Out[1]:(3/2)^(1/2)`
Added 3 more tests in test_printing.cpp to test the fix.
```
In[1]: (Integer(23))*((Integer(5)/2)**(Integer(1)/2))*((Integer(7)/3)**(Integer(1)/2))
Out[1]: 23*(7/3)^(1/2)*(5/2)^(1/2)
In[2]: ((symbols('x')/2)**(Integer(1)/2))
Out[2]: ((1/2)*x)^(1/2)
In [3]: (Integer(3)/2)**(Integer(1)/3)
Out[3]: (3/2)^(1/3) 
```

Fix to the missing parentheses issue #380

---

benchmarks/CMakeLists.txt
benchmarks/eval_double1.cpp

We construct a longer expression (as long as possible but not long enough to
trigger stack overflow problem due to too many recursion calls in eval_double)
and then call eval_double() on it many times.
This is ready to go in. @isuruf would you mind reviewing it?

Add a benchmark for eval_double()

---

src/pow.cpp
src/tests/basic/test_arit.cpp

The problem was that sqrt(2)*sqrt(2) = 2 was left in the Mul's dictionary, so
we needed to use dict_add_term_new(), which moves the coefficient 2 from the
dictionary into the overall coefficient.
A test was added. Fixes #397.

Fix ((sqrt(2)+sqrt(2)*x)**2).expand()

---

src/pow.cpp
src/tests/basic/test_arit.cpp

After expanding base of pow, return the new base to the power exp if pow is not further expandable

Fix expand((x+1)**2-x**2-2*x)**2)

---

src/mul.cpp

Timing for `(x*(x+1)*....(x+100)).diff(x)` improved to 1.05 ms from 2.14 ms.

Speedup Mul::diff and Mul::power_all_terms

---

src/pow.cpp
src/tests/printing/test_printing.cpp

Before:
```
In[1]: 2**x
Out[1]: 2^x
```
After:
```
In[1]: 2**x
Out[1]: 2**x
```
The previous tests were also updated. Fixes #403

printing: printing of pow changed to match SymPy

---

src/complex.cpp
src/complex.h
src/mul.cpp
src/pow.cpp
src/tests/basic/test_arit.cpp

Earlier the test
```C++
r1 = mul(sqrt(x), x);
```
would result in a segfault because the type is not checked before casting.

Check for type before casting in Mul::dict_add_term_new

---

bin/install_travis.sh

This reduces the time of the test with `WITH_ARB` from 15 minutes average to 4 minutes.

Build arb, flint and primesieve with simultaneous jobs

---

src/visitor.cpp
src/visitor.h

Should the Visitor classes stay in `visitor.h` or are they supposed to be in `visitor.cpp`?

Change HasSymbolVisitor to subclass from BaseVisitor

---

src/cwrapper.h
src/matrix.h
src/mul.cpp
src/mul.h
src/ntheory.cpp
src/pow.cpp
src/pow.h
src/tests/basic/test_arit.cpp

Changed ^ to ** in comments of all source as well as test files, 
so as to maintain uniformity throughout.
The printing of power was previously changed from ^ to ** in https://github.com/sympy/symengine/pull/404.

Changed ^ to ** in comments

---

CMakeLists.txt
README.md
cmake/FindTCMALLOC.cmake

Fixes #452 
Checks for both `tcmalloc` and `tcmalloc-minimal`
When installing only `tcmalloc-minimal` in Ubuntu, `libtcmalloc-minimal.so.4` is not symlinked with the unversioned `libtcmalloc-minimal.so`. (https://bugs.launchpad.net/ubuntu/+source/google-perftools/+bug/1219685)

Optionally link tcmalloc

---

csympy/lib/csympy.pxd
csympy/lib/csympy_wrapper.pyx
src/CMakeLists.txt
src/basic.h
src/complex_double.cpp
src/complex_double.h
src/eval_arb.cpp
src/eval_double.cpp
src/printer.cpp
src/printer.h
src/real_double.cpp
src/real_double.h
src/tests/basic/test_arit.cpp
src/visitor.cpp
src/visitor.h

This class would keep a `std::complex<double>`
I implemented some not implemented methods in `RealDouble` as well.
For eg. now `1+2*I + 0.2` gives `1.2 + 2.0*I`.
This way, the fact that the imaginary part is exact is lost though.

ComplexDouble

---

src/integer.cpp
src/integer.h

This provides a nice few percent speedup in e.g. the expand2 benchmark.

Use initializer list for Integer::Integer()

---

cmake/checkgmpxx.cpp
symengine/add.cpp
symengine/basic-inl.h
symengine/basic.cpp
symengine/basic.h
symengine/complex.cpp
symengine/complex_double.cpp
symengine/complex_double.h
symengine/constants.h
symengine/functions.cpp
symengine/functions.h
symengine/integer.cpp
symengine/integer.h
symengine/mul.cpp
symengine/polynomial.cpp
symengine/polynomial.h
symengine/pow.cpp
symengine/rational.cpp
symengine/rational.h
symengine/real_double.cpp
symengine/real_double.h
symengine/symbol.h
symengine/tests/basic/test_basic.cpp
symengine/tests/basic/test_functions.cpp
symengine/tests/basic/test_polynomial.cpp
symengine/tests/printing/test_printing.cpp
symengine/visitor.cpp

Now the raw `new` is never used in SymEngine, except in the implementation of `make_rcp`. That way, there is no possibility of a segfault or undefined behavior in Debug mode, since the raw pointer returned by `new` is immediately passed into `rcp`, and one never does this by hand, only by calling `make_rcp`.
The `get_rcp` and `get_rcp_cast` methods return a safe `rcp(this)`. So the new rule is that not only the raw `new` is never used, but also raw `rcp` is never used anymore.
As a bonus, by adding few ifdefs, one can now use Teuchos::RCP in Debug mode and it works. Teuchos::RCP is 100% safe in Debug mode (it has sophisticated dangling pointers and other checks), unlike our own implementation of RCP. In Release mode, we still use our own implementation because it is faster. Now we can get …

Implement make_rcp, get_rcp, get_rcp_cast and use it

---

README.md

I think it should be either
`CXX=clang++ cmake .` or `CC=clang cmake .`
Because `CXX=clang cmake .` doesn't work on my machine.
Close this if I am wrong.
@certik @isuruf

Fix typo in compiler choice CMake

---

symengine/rings.cpp

Nice speedup obtained using FMA in `poly_mul`.
`expand2b` average falls from `95ms` to `60ms` on my machine.
As suggested by @bluescarni
PS: There may be other areas throughout SymEngine where we can use this, something to keep in mind.

Use mpzaddmul for poly_mul

---

CMakeLists.txt
symengine/symengine_assert.h
symengine/symengine_rcp.h

En route to fixing https://github.com/sympy/symengine/issues/482
/cc @certik @isuruf

Make SYMENGINE_ASSERT use custom assert instead of assert()

---

symengine/python/symengine/tests/test_matrices.py

The same as the patch I sent, but now I have a GitHub account.

Fix typo in test_matrices.py

---

.travis.yml

`binutils-dev` was added to apt-whitelist of Travis-CI , so now we can use it in Travis-CI
https://github.com/travis-ci/travis-ci/issues/4113

Use BFD for travis tests

---

symengine/python/symengine/lib/symengine.pxd
symengine/python/symengine/lib/symengine_wrapper.pyx
symengine/python/symengine/tests/test_matrices.py

Add bounds checking for `get`, `set` and `submatrix`. Previous methods are renamed to `_get`, `_set`, `_submatrix` respectively.
Also operator overloads for *, + and indexing added.

Improve python wrappers for matrix

---

symengine/printer.cpp
symengine/tests/printing/test_printing.cpp

Previously `1.0` would just print as `1` and now `.0` is added at the end.

Improve printing of doubles

---

symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/ruby/ext/symengine/ruby_basic.c
symengine/tests/cwrapper/test_cwrapper.c

This makes the functions consistent with `basic_new_heap()` and `basic_free_heap()`. Documentation was improved to explain this issue.

Rename basic_init() to basic_new_stack() and basic_free() to basic_free_stack()

---

cmake/FindPython.cmake

`get_config_var('LIBDIR')` is none in Windows and wrong in Sage. This PR resolves this issue.

Improve FindPython.cmake

---

symengine/ruby/notebooks/beginner.ipynb
symengine/ruby/notebooks/differentiation_example.ipynb

I had to add `#to_s` method to the output of every expression to display the output. They are just a temporary workaround. The fact that the `Add`, `Mul` and `Pow` are now converted to `SymEngine::Basic` seems to have broken the expected behaviour of the `#to_iruby` method. I had so written the `#to_iruby` method, that it avoided the instances of purely `Basic` class, since they are uninitialised and cause an error. I will remove them after they(Add/Mul/Pow) are properly represented in Ruby.

Updated the beginner notebook and added example notebook

---

.travis.yml
bin/install_travis.sh

@isuruf this works with `sudo: false` and it avoids saving the tarball. Here is a successful run: https://travis-ci.org/certik/symengine/jobs/75348011
The tarball itself is pretty big, since I use the tar.gz tarball, but as the next iteration, we can figure out how to use the lrzip tarball, which is 2x smaller --- I implemented it in #588, but that issue depends on Travis whitelisting `lrzip`, so for now if this PR works, I would suggest to merge it and we can improve upon it later.

Install Sage from a tarball

---

.travis.yml

It seems this test has never failed, so we should just always run it.

Move the Sage test into "cannot fail" section

---

symengine/CMakeLists.txt
symengine/lambda_double.h
symengine/tests/eval/CMakeLists.txt
symengine/tests/eval/test_lambda_double.cpp

This is from https://github.com/symengine/symengine/pull/603
It is an alternative to https://github.com/symengine/symengine/pull/621 which introduces a deferred exception.
This relies on choosing real/complex at instantiation of `Lamdify` from Python instead of at `__call__`.
cherry-picked from https://github.com/isuruf/symengine/commit/c0f757c4274c1eba7d48ffb899f81da6ae5eec64
~~Note: tests from #621 are still missing in this PR.~~ (they are in since 7248c1c)

Use C++ lambda expressions for Lambdify (no deferred exception)

---

cmake/LibFindMacros.cmake

CMake's `function` has variable scopes while `macro` is textual replacements, which is not desirable when defining temporary variables inside a macro which are used elsewhere.

Change libfind macro to function

---

symengine/mul.cpp
symengine/mul.h
symengine/pow.cpp
symengine/tests/basic/test_arit.cpp
symengine/tests/printing/test_printing.cpp

`sqrt(-2*x*y)` is expanded to `sqrt(2)*sqrt(-x*y)`
`pow(sqrt(x*y)*x, 2)` is expanded to `x**3*y`
Background: https://gitter.im/sympy/sympy?at=561260400b9059c80b7a5d0e was hitting not canonical errors and with this PR, all expressions are canonical.

Fix not canonical bugs

---

symengine/eval_arb.cpp
symengine/eval_double.cpp
symengine/eval_mpc.cpp
symengine/eval_mpfr.cpp
symengine/functions.cpp
symengine/functions.h
symengine/tests/basic/test_functions.cpp

This is to make a distinction between `FunctionSymbol` and other user defined functions

Change FunctionWrapper as the base class for user defined functions

---

appveyor.yml

Path of sh.exe changed in appveyor and it is interfering with MinGW builds. Renaming sh.exe in the updated path to fix it.

Update renaming sh.exe 

---

.travis.yml
bin/install_travis.sh
symengine/dict.h

Enabling C++11 features in latest gmp requires user-defined literals which is only avaiable in gcc-4.7
GCC version was not upgraded to 4.8 because MSVC is lacking features in gcc-4.8

Update gcc to 4.7 and enable C++11 in libgmpxx

---

symengine/dict.h

There is no need of having `vec_int_eq` functor. `operator==` is already defined for `vector<'T>`s. ref : http://en.cppreference.com/w/cpp/container/vector/operator_cmp.

Remove vec_int_eq

---

symengine/expand.cpp
symengine/tests/basic/test_arit.cpp

`a_coef` was already multiplied by `multiply`. Removed the extra multiplication.
Fixes #705

Fix for #705

---

symengine/eval_arb.cpp
symengine/eval_double.cpp
symengine/eval_mpc.cpp
symengine/eval_mpfr.cpp
symengine/expand.cpp
symengine/lambda_double.h
symengine/printer.cpp
symengine/printer.h
symengine/tests/printing/test_printing.cpp
symengine/visitor.cpp
symengine/visitor.h

With this approach to extend `StrPrinter` you can do 
```C++
class MyStrPrinter : public BaseVisitor<MyStrPrinter, StrPrinter> {
public:
using StrPrinter::bvisit;
}
```
and override existing bvisit methods or add new ones. I'll add this to a new wiki page.
Source: https://katyscode.wordpress.com/2013/08/22/c-polymorphic-cloning-and-the-crtp-curiously-recurring-template-pattern/

Make BaseVisitor extensible

---

symengine/add.cpp

I checked benchmarks. Improvements in `expand6` (from 5604ms to 5077ms) and `expand7` (4586ms to 3752ms). No visible change in `expand2` and `add1`

Speedup Add::__hash__()

---

.travis.yml
bin/install_travis.sh

Travis does an additional compiling with gcc 5.2 and g++ 5.2(latest versions)
#684

Latest gcc Travis checks

---

symengine/CMakeLists.txt
symengine/add.cpp
symengine/add.h
symengine/basic-methods.inc
symengine/basic.h
symengine/complex.h
symengine/complex_double.h
symengine/complex_mpc.h
symengine/constants.cpp
symengine/constants.h
symengine/derivative.cpp
symengine/functions.cpp
symengine/functions.h
symengine/integer.h
symengine/mul.cpp
symengine/mul.h
symengine/number.cpp
symengine/number.h
symengine/polynomial.cpp
symengine/polynomial.h
symengine/pow.cpp
symengine/pow.h
symengine/rational.h
symengine/real_double.h
symengine/real_mpfr.h
symengine/series.h
symengine/symbol.cpp
symengine/symbol.h

For now, I just removed `accept` and `diff`. This will work for everything, like `subs`, etc.
This works similar to the visitor pattern, except that only a single virtual function call is used.
By using the @isuruf's trick with the `bvisit` inline methods, this PR implements all derivatives as `DiffImplementation::diff` static methods.
Performance should not be affected by this PR.

Remove methods from core

---

cmake/FindTCMALLOC.cmake
cmake/LibFindMacros.cmake

If the library is not found, it will have a string ending with `-NOTFOUND`,
which is evaluated as False by cmake.

Just use ${LIBNAME}_LIBRARY

---

cmake/LibFindMacros.cmake

That variable doesn't seem to be needed: https://cmake.org/cmake/help/v3.0/command/find_path.html

Remove PATH_SUFFIXES from find_path

---

bin/install_travis.sh
bin/test_travis.sh

Fix for #763 
@isuruf @Sumith1896

Shift Travis whitespace check to the end

---

.travis.yml

Since the code quality script was replaced, this line is no more necessary.
Also any specific reason why other lint checks mentioned in #743 were not implemented?
@isuruf @certik

Minor fix in .travis.yml

---

symengine/eval_mpc.cpp
symengine/eval_mpfr.cpp
symengine/tests/eval/test_eval_mpc.cpp
symengine/tests/eval/test_eval_mpfr.cpp

Fix for #701 .
From euler constant(0.577) to euler's number(2.718)
@isuruf @abhinavagarwal07

Changed euler constant to euler number in eval_mpfr and eval_mpc

---

CMakeLists.txt
README.md
benchmarks/CMakeLists.txt
benchmarks/series_expansion_sincos_flint.cpp
benchmarks/series_expansion_sincos_piranha.cpp
symengine/CMakeLists.txt
symengine/series.h
symengine/series_flint.cpp
symengine/series_flint.h
symengine/series_visitor.h
symengine/symengine_config.h.in
symengine/tests/basic/CMakeLists.txt
symengine/tests/basic/test_series_expansion_URatF.cpp
symengine/type_codes.inc
symengine/visitor.h

Flint polys cannot do `cot()`, `csc()`, and `lambert_w()` because they cannot handle Laurent polys.

Flint univariate series expansion

---

symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/tests/cwrapper/test_cwrapper.c

I have experimented on how the interface for the SymEngine's constants from C should be.
The logic was the `basic_struct*` that we obtain from these functions should not be available for referencing to any other `basic_struct`, i.e. it should be `const`. Some changes needed to be made to support that.
@certik @isuruf Please have a look.

Constants in C wrappers

---

symengine/series_flint.h

Timings of `benchmark/series_sincos_flint` are:
* before (using old Flint): 1620 ms
* before (using own code): 605 ms
* now (using flint git master, removing own code): 125 ms

series_flint: take advantage of newest flint

---

symengine/parser.cpp
symengine/series.h
symengine/tests/basic/test_functions.cpp
symengine/tests/basic/test_parser.cpp

Added some missing functionality to the parser, including multi argument function support. (and also some newly added functions)
Also added some tests to check if errors were being thrown correctly.
Also, the current master has trailing whitespaces, which I removed. Why are they creeping in (repeatedly), and why isn't travis reporting them?

Misc parser

---

symengine/tests/basic/test_parser.cpp

Since gamma is not imported from SymEngine, compiler thinks it is a deprecated
function in OS X math library, but ADL finds the correct SymEngine function

Fix OS X warning

---

symengine/functions.cpp
symengine/tests/basic/test_functions.cpp

LambertW(-e^(-1)) is -1. Was previously incorrect.
Fixes #853

fixed small bug in lambertw

---

benchmarks/CMakeLists.txt
benchmarks/bench_eval_double.cpp
benchmarks/eval_double1.cpp
symengine/basic-methods.inc
symengine/eval_double.cpp
symengine/eval_double.h

This implements both approaches for `eval_double`, so that we can benchmark them side by side.

Better benchmarks for 'eval_double'

---

symengine/add.cpp
symengine/add.h
symengine/tests/basic/test_basic.cpp

I propose to fix compile problems in symengine.py by putting back the removed function

revert commit 1617f970; Add::as_two_terms() needed by symengine.py

---

README.md

Fixes #900
<br/>I think this can be merged without any effect on the clang format PR.
@isuruf

Add 'make install' to readme

---

symengine/polynomial.cpp
symengine/polynomial.h

- removed the unecessary `dict_add_term` function
- Also removed `SYMENGINE_ASSERT` from vector constructor, because the polynomial formed is guaranteed to be canonical
- UnivariateInt had an incorrect `is_canonical`, for the 0 polynomial
- minor formatting/style changes in `from_dict`
- `mul_poly` was initially constructing a redundant vector (which could be too inefficient for sparse polys) Now uses `from_dict`. Constructs the dictionary on the go
More minor changes to follow.
@isuruf @Sumith1896

Minor changes in Univariate polynomials

---

symengine/CMakeLists.txt
symengine/add.cpp
symengine/add.h
symengine/basic-inl.h
symengine/basic.cpp
symengine/basic.h
symengine/functions.cpp
symengine/functions.h
symengine/mul.cpp
symengine/mul.h
symengine/pow.cpp
symengine/pow.h
symengine/subs.h
symengine/tests/basic/test_subs.cpp
symengine/visitor.h

msubs is to be used as a replacement for `sympy.physics.mechanics.functions.msubs`
Depends on #923

Refactor subs into a visitor and add msubs

---

bin/test_format_local.sh
bin/travis_clang.sh

Now travis-ci prints the diff of the correct format
bin/test_format_local.sh can be used as a pre-commit git hook

Improve clang-format

---

benchmarks/series.cpp
symengine/polynomial.h
symengine/series_generic.cpp
symengine/tests/basic/test_polynomial.cpp

The functions `from_dict`, `from_vec` and `create` have been removed from the `UnivariateIntPolynomial` class, essentially because they were not needed. Also, the method `univariate_int_polynomial` function has been overloaded to take in both dictionaries and vectors, to construct the polynomial. 
In the `univariate_int_polynomial`, for singletons in dictionaries, we explicitly have to tell the type (vector or dic) (otherwise it is an ambiguous function call).  ie
```
T = univariate_int_polynomial(x, map_uint_mpz{{0, 2_z}});
REQUIRE(T->__str__() == "2");
U = univariate_int_polynomial(x, std::vector<integer_class>{{0_z, 2_z}});
REQUIRE(U->__str__() == "2*x");
```
Have made these changes wherever required. Also, some add, sub and neg tests were changed.

removed redundant function `create`

---

.gitignore
benchmarks/series.cpp
symengine/dict.cpp
symengine/dict.h
symengine/expand.cpp
symengine/polynomial.cpp
symengine/polynomial.h
symengine/printer.cpp
symengine/series_generic.cpp
symengine/tests/basic/test_polynomial.cpp
symengine/tests/basic/test_series_generic.cpp
symengine/tests/printing/test_printing.cpp

* Ignore flint executables
* Changed mul_uni_poly parameters to const & instead of RCP UnivariatePolynomial
* UnivariatePolynomial wraps UnivariateExprPolynomial, which has map_int_Expr dict; progress on changes to series_generic use of UnivariateExprPolynomial
* Add constant multiplication condition for faster performance, UnivariateExprPolynomial benchmark tests
* Refactor UnivariateSeries and most of its tests to work with new UnivariateExprPolynomial except as_basic(), moved 0 checking in UnivariatePolynomial to UnivariateExprPolynomial
* Check for 0 terms in all UnivariateExprPolynomial constructors, uncomment rest of test_series_generic
* Resolve conflicts

Structure change of UnivariateExprPolynomial and UnivariatePolynomial

---

symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/tests/cwrapper/test_cwrapper.c

Wrappers for Real Double

---

symengine/CMakeLists.txt

When using SymEngine in an external C++ program the include files were not installed properly to include the new polys subfolder that was recently added. I changed CMakeList.txt to reflect there changes.

CMake fixes for new upolys

---

symengine/integer.cpp
symengine/series.h
symengine/series_visitor.h
symengine/tests/basic/test_series_generic.cpp

While testing multivariable series expansion, I found a few bugs in `series.h`.  Since multivariable expansion is not quite ready yet and these bugs are in code that's already out there, I'm submitting these fixes in a separate PR.  
It seems that the functions in `series.h` were not tested on inputs with nonzero constant terms, so I've also added some tests to that effect.

Bugfixes for series.h

---

symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/tests/cwrapper/test_cwrapper.c

Needed for https://github.com/symengine/symengine.rb/pull/46

Implementing real_double_get_d method

---

symengine/polys/uexprpoly.cpp
symengine/polys/uexprpoly.h
symengine/polys/uintpoly.cpp
symengine/polys/uintpoly.h
symengine/polys/upolybase.h
symengine/tests/polynomial/test_uexprpoly.cpp
symengine/tests/polynomial/test_uintpoly.cpp

In the last commit, I removed `is_canonical`. What I basically do is always force only canonical polynomials to be formed (in the constructors itself).
The (new) constructors should remain specific to the derived class, as they will be different for Flint and Piranha polynomials. The methods `from_dict` and `from_vec` now call the constructors of the derived class, have been moved to the base class. 
@isuruf  @Sumith1896 
Edit : removed the last commit

Misc poly changes

---

.travis.yml

LLVM apt repository temporary down.
Only last commit needs to be reverted when LLVM apt repository comes back up.

Move clang-format to allow_failures

---

CMakeLists.txt

These are no longer used in SymEngineConfig.cmake after changes done in PR675

Remove installing cmake find modules

---

symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/real_mpfr.h
symengine/tests/cwrapper/test_cwrapper.c
symengine/tests/eval/test_eval_mpfr.cpp

I am having trouble testing the MPFR code so far, as the cmake sets WITH_MPFR to false. I tried to change the [`CMakeLists.txt`] (https://github.com/symengine/symengine/blob/adb297e1d635ca8a7ffe3616067f13b5e131b358/CMakeLists.txt#L168) to no avail. I have installed `libmpfr4` and `libmpfr-dev` on system, in case that is needed. What am I missing here?

[WIP] Wrappers for Real MPFR and Complex MPC

---

symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/tests/cwrapper/test_cwrapper.c

Wrappers for the FunctionSymbol class

Function symbol CWrappers

---

symengine/derivative.cpp
symengine/dict.h
symengine/expand.cpp
symengine/ntheory.cpp
symengine/ntheory.h
symengine/polys/uexprpoly.h
symengine/polys/uintpoly.cpp
symengine/polys/uintpoly.h
symengine/polys/uintpoly_flint.cpp
symengine/polys/uintpoly_flint.h
symengine/polys/uintpoly_piranha.cpp
symengine/polys/uintpoly_piranha.h
symengine/polys/upolybase.h
symengine/printer.cpp
symengine/tests/ntheory/test_ntheory.cpp
symengine/tests/polynomial/test_mintpoly.cpp
symengine/tests/polynomial/test_uintpoly.cpp
symengine/tests/polynomial/test_uintpoly_flint.cpp
symengine/tests/polynomial/test_uintpoly_piranha.cpp
symengine/tests/printing/test_printing.cpp

flint : `gcd`, `lcm`, `multieval`, `pow` and `divides` 
symengine : `pow` and `multieval`(slow) (`gcd`, `lcm` & `divides` requires rational polys)
nothing new for piranha as of yet
new typedef `vec_integer_class`
removed function `uint_poly`
Edit : All 3 classes now have `multieval`, `pow` and `divides` and `get_lc`
Flint and piranha also have `gcd` and `lcm`

more poly functionality

---

bin/test_travis.sh
symengine/derivative.cpp
symengine/flint_wrapper.h
symengine/polys/uintpoly_flint.cpp
symengine/polys/uintpoly_flint.h
symengine/polys/upolybase.h
symengine/rational.h
symengine/series_flint.cpp
symengine/series_flint.h
symengine/series_piranha.cpp
symengine/tests/basic/test_basic.cpp
symengine/tests/polynomial/test_uintpoly_flint.cpp

This removes any use of flintxx, so please don't reintroduce it.

polys: use Flint C API instead of C++ API 

---

.travis.yml
symengine/derivative.cpp
symengine/flint_wrapper.h
symengine/polys/uintpoly_flint.cpp
symengine/polys/uintpoly_flint.h
symengine/polys/upolybase.h
symengine/series_flint.h
symengine/tests/basic/test_series_expansion_URatF.cpp

* This is extension of #1001. 
* Since LLVM apt repository is back up, the allowed failures are removed.

Moving clang-format back to main tests

---

symengine/mp_class.h
symengine/tests/ntheory/test_ntheory.cpp

Special case negative numbers b for a**b mod m
gmp does the correct thing for `b`, but flint is undefined for `b` < 0.

Fix mp_powm of Flint

---

symengine/add.cpp
symengine/add.h
symengine/tests/basic/test_basic.cpp

Something like this is needed to provide SymPy's `x.as_coefficients_dict`, see https://github.com/symengine/symengine.py/issues/59
If you can think of a better interface, share your thoughts please.

safe accessors to Add::coeff_ and dict_

---

symengine/derivative.cpp
symengine/functions.cpp
symengine/series.cpp
symengine/series_visitor.h
symengine/tests/basic/test_basic.cpp
symengine/tests/basic/test_series_generic.cpp
symengine/visitor.cpp
symengine/visitor.h

Take 3. There is still a coverage fail which led me to the investigation of a hidden bug in series_visitor.h (probably). Later.

has_symbol(): replace unnecessary RCP function arg

---

symengine/functions.cpp
symengine/tests/basic/test_functions.cpp

Fix for #921. Enabled function `get_pi_shift()` to account for `arg == 0` case
```python
sec(0) = 2*2**(1/2)/(1 + 3**(1/2))
csc(0) = -4/(-1 + 5**(1/2))
```
```python
sec(0) = 1
csc(0) # returns " libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: div: Division by zero "
```

Improved sec(x) and csc(x) functions for x = 0 case

---

symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/tests/cwrapper/test_cwrapper.c

In order to implement, <,<=,> and >= for numbers in Ruby Wrappers.
They are required for the tests of evalf function.

Sign check for Numbers

---

symengine/fields.cpp
symengine/fields.h
symengine/tests/basic/test_fields.cpp

Equal Degree Zassenhaus's algorithm

Equal degree

---

symengine/tests/logic/test_logic.cpp

I'm not sure why, but `REQUIRE(str.find(c1->__str__()) != std::string::npos);` was giving a segfault all of a sudden. Same test case, but changed the way it was tested.

Fix segfault in mingw

---

.travis.yml
bin/trigger_feedstock.sh

On every merge this would trigger a conda build and upload to `symengine/label/dev` and on tags it will upload to `symengine`. Version is calculated using `git describe --tags` which includes the commit hash in it.

Trigger Conda build on merge

---

bin/install_travis.sh
symengine/polys/uintpoly_piranha.h

PZERO is a macro in some system headers and conflicts with symengine's definition
Fixes #1083
Fixes #1085
@jppelteret, can you confirm that this fixes the problem for you?
Btw, what is the OS you are building symengine on?

rename PZERO -> pzero

---

symengine/infinity.cpp
symengine/series_generic.cpp
symengine/symengine_exception.h
symengine/tests/basic/test_series_generic.cpp

My local system gave me a lot of issues (clock skew, installation etc.). I believe most of them are resolved now and hence i would like to put forward a fresh pull request for #1089.
Fixes #1089

A Better Update to Issue #1089

---

benchmarks/CMakeLists.txt
benchmarks/symengine_bench.cpp
benchmarks/symengine_bench.m
benchmarks/symengine_bench.mpl
benchmarks/symengine_bench_ginac.cpp

Even though this involves a series, the coefficients are symbolics
and therefore benchmarks both the series function and symbolic
arithmetics.
NOTE: this is a pretty good benchmark when you want to check if
a change in symengine, slows down symbolic arithmetic.

Add a benchmark for general symbolic arithmetic and series

---

symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/tests/cwrapper/test_cwrapper.c

Added a function to call to indicate whether some components (namely flint, arb, mpc and mpfr) are installed or not. No tests are added (to prevent travis build failures). However the following links may be referred to for cross-checking the functionality:
(Build #9 For Rejecting Non MPFR builds)
https://travis-ci.org/ShikharJ/symengine/builds/172672603
(Build #8 For Rejecting MPFR builds)
https://travis-ci.org/ShikharJ/symengine/builds/172666980
The above tests have been conducted by patching the following lines of code:
char *s = "mpfr";
(#9)SYMENGINE_C_ASSERT(symengine_have_component(s));
(#8)SYMENGINE_C_ASSERT(!symengine_have_component(s));

Added Function for Issue #1088 (Second Feature)

---

symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/tests/cwrapper/test_cwrapper.c

Relevant: Issue #1088 Feature 3.
For the course of development refer: PR #1122.

complex_double_get function

---

.travis.yml
bin/install_travis.sh
bin/test_travis.sh

There are two dependencies not on conda-forge.
- GMP ECM - This doesn't provide a fat binary type as in gmp, but does have inline assembly. I'm not sure how to package this
- Piranha - I'll get this done within a few weeks.

Use conda for binaries

---

symengine/cwrapper.cpp
symengine/cwrapper.h

Fixed, this is from my fork.
I've wrapped `vecbasic_push_back` and `vecbasic_get` with the `CWRAPPER` macros.

wrapped vecbasic_* calls in CWRAPPER

---

symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/tests/cwrapper/test_cwrapper.c

Add c wrapper code for `mod_f` and `quotient_f` function in `ntheory` module, as well as corresponding test cases. Fix issue #939.

Wrap ntheory_mod_f and ntheory_quotient_f in C.

---

symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/tests/cwrapper/test_cwrapper.c

~~This PR includes a function called `outArg_Integer` to make values with type `Ptr<RCP<const Integer>>`, which are commonly used in module [ntheory.h](https://github.com/symengine/symengine/blob/master/symengine/ntheory.h).~~
New wrapped functions are as follows:
+ `ntheory_gcd_ext`
+ `ntheory_quotient_mod`
+ `ntheory_quotient_mod_f`
+ `ntheory_mod_inverse`
+ `ntheory_fibonacci2`
+ `ntheory_lucas2`
+ `ntheory_factorial`

Wrap more functions in ntheory.h.

---

symengine/printer.cpp
symengine/tests/printing/test_printing.cpp

Please suggest any necessary changes if required.
Fixes #1133

Fix for Issue #1133 with Test

---

.travis.yml
bin/install_travis.sh
symengine/symengine_assert.h
symengine/utilities/catch/catch.hpp
symengine/utilities/teuchos/Teuchos_RCPNode.cpp
symengine/utilities/teuchos/Teuchos_RCPNode.hpp

Relevant: #1134 
@isuruf @certik  `-Wno-error=terminate` has been added for now.  What should be our approach? Should we modify the teuchos library code or rather suppress the  `-werror=terminate` flag?

Added a GCC 6 Build to Travis

---

symengine/cwrapper.cpp
symengine/eval_double.cpp
symengine/fields.cpp
symengine/polys/msymenginepoly.h
symengine/polys/upolybase.h
symengine/tests/basic/test_basic.cpp
symengine/tests/basic/test_functions.cpp
symengine/tests/basic/test_number.cpp
symengine/tests/basic/test_parser.cpp
symengine/tests/printing/test_printing.cpp

Some more simple fixes for #1139.
The commits currently cover:
```
cwrapper.cpp
test_basic.cpp
test_parser.cpp
test_functions.cpp
test_printing.cpp
test_number.cpp
```
Additionally, I feel that our use of static_cast() in the following files is essential, as only type conversions are done there, (and no Base-to-Derived or Derived-to-Base pointer changes):
```
basic-inl.h
test_evalf.cpp
```

Additional Fixes for #1139

---

CMakeLists.txt

Fixes warning for CMake policy CMP0042 when building shared libraries on
MacOS. Also prevents linking errors when incorporating SymEngine into
other projects.
Fixes #1148

Enable rpath on MacOS.

---

symengine/real_double.cpp
symengine/tests/basic/test_functions.cpp

@jppelteret, thanks for the bug report.
FYI `eval_double` is for evaluating things like `sec(3)` which is kept as it is, whereas `sec(3.0)` is evaluated automatically as in `real_double.cpp`. One difference is that `eval_double(asin(-2))` becomes NaN, but `asin(-2.0)` becomes `-1.5707963267949 + 1.31695789692482*I`
@certik, I'm going to increase test coverage of `real_double.cpp` over the weekend, but till then this should be good to go.
Fixes #1157

Fix sec(RealDouble) and csc(RealDouble)

---

symengine/infinity.cpp
symengine/infinity.h
symengine/tests/basic/test_infinity.cpp

As always, please review and suggest changes.

Implemented Infty::pow and Infty::rpow functions

---

symengine/pow.cpp
symengine/tests/basic/test_arit.cpp
symengine/tests/basic/test_subs.cpp
symengine/tests/polynomial/test_mexprpoly.cpp

When i tried to port SymEngine's pow function to the way SymPy does it ,i found that there is a complementary bug in test_mexprpoly.cpp where x^-1 is evaluated for x as 0.
Until now , It didn't raised (0*Inf) error as 1/0 was evaluated to 0.So I changed that part as well in the same commit.Please review this bug fix and suggest changes. 
Fixes #1154

Fix for #1154

---

symengine/complex.h
symengine/integer.cpp
symengine/mul.cpp
symengine/rational.cpp
symengine/rational.h
symengine/tests/basic/test_basic.cpp
symengine/tests/basic/test_functions.cpp

div(2,0) in SymEngine throws DivisionByzeroError. But I think returning ComplexInf instead is a better way.I crosschecked this with SymPy and it does the same (returns ComplexInf for div(2,0)).So I Changed all such possible instances of throwing error to ComplexInf.
@isuruf  @certik  Please review and Suggest changes.

use ComplexInf instead of throwing DivisionByZero error

---

symengine/complex_mpc.cpp
symengine/number.h
symengine/pow.cpp
symengine/real_double.cpp
symengine/real_mpfr.cpp
symengine/tests/basic/test_arit.cpp
symengine/tests/eval/test_eval_double.cpp

@isuruf I'am not confident that this is the expected implementation. Please review and suggest improvements.
Fixes #1174

Automatic Evaluation of pow(RealDouble, Constant)

---

symengine/complex_mpc.cpp
symengine/number.h
symengine/pow.cpp
symengine/real_double.cpp
symengine/real_mpfr.cpp
symengine/tests/eval/test_eval_double.cpp

constant function was different from other functions in Evaluate, and also doesn't give a way to handle exp(Inf) or exp(Series).

Add evaluate to exp and remove constant

---

symengine/mp_class.h

Otherwise mp_class.h cannot be at the top of a file after preprocessing.

Include symengine_config.h at the top of mp_class.h

---

symengine/complex_mpc.cpp
symengine/functions.cpp
symengine/infinity.cpp
symengine/number.h
symengine/real_double.cpp
symengine/real_mpfr.cpp
symengine/tests/basic/test_functions.cpp
symengine/tests/basic/test_infinity.cpp
symengine/tests/eval/test_eval_mpc.cpp

This is a rebase of #1192 without the binary.

add erf and erfc in evaluate class #1192

---

symengine/tests/basic/test_arit.cpp
symengine/tests/basic/test_basic.cpp
symengine/tests/basic/test_functions.cpp
symengine/tests/basic/test_infinity.cpp
symengine/tests/basic/test_nan.cpp
symengine/tests/basic/test_rational.cpp
symengine/tests/cwrapper/test_cwrapper.c
symengine/tests/eval/test_eval_mpfr.cpp
symengine/tests/ntheory/test_ntheory.cpp
symengine/tests/printing/test_printing.cpp

Please review and suggest improvements.

Misc Test Improvements

---

symengine/functions.cpp
symengine/nan.cpp
symengine/nan.h
symengine/tests/basic/test_nan.cpp

like for log(Nan) ..master throws an error message of Not Implemented.
Instead returning Nan is a better way.
TO-DO - 
~~- [ ] for functions not in evaluate class check if arg is Nan and return Nan there itself.~~
@isuruf  please review and suggest changes.

add evaluate class for nan

---

symengine/derivative.cpp
symengine/functions.cpp
symengine/functions.h
symengine/tests/basic/test_functions.cpp

Relevant: #814 
This PR is a proposed improvement over #1120 by @vishusidana95, which I felt, wasn't along the lines of SymPy's method of execution. As always, please review and suggest improvements.

Improvements over #1120

---

symengine/fields.h
symengine/polys/basic_conversions.h
symengine/polys/uintpoly_flint.h
symengine/polys/uintpoly_piranha.h
symengine/polys/upolybase.h
symengine/polys/usymenginepoly.h
symengine/tests/polynomial/test_basic_conversions.cpp

@isuruf please see
Now I feel what you were saying about code simplicity is correct. This `BaseType` solution feels a little too compliacted. I am still thinking of alternatives.
Basically, most of the function definitions are in base classes like `UIntPolyBase`/`URatPolyBase` while their implementations in `USymEnginePoly`/`UFlintPoly` etc.
Initially, I though multiple inheritance would work, ie, inherit from the base class and then inherit from the implementation class. But the compiler does not treat the implementation with their respective definitions (signature mismatch?). Do you have any alternative suggestions for the overall structure?

make duplicate code common, uratpoly

---

symengine/functions.cpp

numerator = zero case is already handled in the previous [if](https://github.com/symengine/symengine/blob/master/symengine/functions.cpp#L1094) statement.

remove redundant check

---

symengine/parser.cpp
symengine/tests/basic/test_parser.cpp

This checks for unicode bytes and treats each byte as a ASCII char.
Fixes #1230

Allow unicode in the parser

---

symengine/complex_mpc.cpp
symengine/functions.cpp
symengine/functions.h
symengine/parser.cpp
symengine/real_double.cpp
symengine/real_mpfr.cpp
symengine/tests/basic/test_arit.cpp
symengine/tests/basic/test_basic.cpp
symengine/tests/basic/test_functions.cpp
symengine/tests/basic/test_infinity.cpp
symengine/tests/basic/test_number.cpp
symengine/tests/basic/test_sets.cpp
symengine/tests/eval/test_eval_mpc.cpp
symengine/tests/eval/test_eval_mpfr.cpp
symengine/tests/eval/test_lambda_double.cpp
symengine/tests/logic/test_logic.cpp

While writing test cases , i came across several bugs as listed below and these are fixed now.
- [acsc()](https://github.com/symengine/symengine/compare/master...ranjithkumar007:TargetCov100%25?expand=1#diff-7adabd929d7b40deac32003312d6f910R281) and [asec()](https://github.com/symengine/symengine/compare/master...ranjithkumar007:TargetCov100%25?expand=1#diff-7adabd929d7b40deac32003312d6f910R286) in real_double.cpp
- [Beta::rewrite_as_gamma()](https://github.com/symengine/symengine/compare/master...ranjithkumar007:TargetCov100%25?expand=1#diff-ccb9531ddf99a9263a8ca4275bdf438eR2758) in functions.cpp
- [acsch()](https://github.com/symengine/symengine/compare/master...ranjithkumar007:TargetCov100%25?expand=1#diff-748ec5462b257fcab8881d2d458be573R904), …

increase coverage and minor bug fixes

---

symengine/CMakeLists.txt

Edited Symengine/CmakeLIsts.txt to add SOVERSION and VERSION in shared libraries. 
SOVERSION used is SYMENGINE_MAJOR_VERSION.SYMENGINE_MINOR_VERSION.
Fixes https://github.com/symengine/symengine/issues/1226

 Version libsymengine.so 

---

CMakeLists.txt
symengine/llvm_double.h

Update the LLVM version check in `llvm_double.h` to accommodate v4.0

Update a LLVM version check

---

symengine/llvm_double.cpp

This fixes a segmentation fault that may arise when sequential calls are
made to the functions defined with this macro.

Remove static keyword from LLVM double ONE_ARG_EXTERNAL_FUNCTION macro.

---

symengine/parser.cpp
symengine/tests/basic/test_parser.cpp

I have just added "oo" and "zoo" to the list of constants which are recognized by the parser.

Added infinity constants (oo, zoo) to parser

---

symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/tests/cwrapper/test_cwrapper.c

I have added `vecbasic_set` and `vecbasic_erase` to the C wrappers. I am using them, may be they are useful for others as well.

Added vecbasic_{ set, erase } to C wrappers

---

symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/tests/cwrapper/test_cwrapper.c

I have replaced these three wrappers
```
CWRAPPER_OUTPUT_TYPE complex_real_part(basic s, const basic com);
CWRAPPER_OUTPUT_TYPE complex_double_real_part(basic s, const basic com);
CWRAPPER_OUTPUT_TYPE complex_mpc_real_part(basic s, const basic com);
```
by just the following one
```
CWRAPPER_OUTPUT_TYPE complex_base_real_part(basic s, const basic com)
{
CWRAPPER_BEGIN
SYMENGINE_ASSERT(is_a<ComplexBase>(*(com->m)));
s->m = (down_cast<const ComplexBase &>(*(com->m))).real_part();
CWRAPPER_END
}
```
And I did analogue changes regarding the `imaginary_part` wrappers.
So all in all 6 wrappers have been replaced by just 2, without loosing any functionality.
Hope you like it!

New C wrappers for real and imaginary part of complex numbers

---

.travis.yml

Fixes #1307.
Currently `llvm-toolchain-trusty-3.7` is not white-listed on `Travis`, so this is running `llvm-toolchain-precise-3.7`. Suggestions?

Update Travis-CI Linux Distribution

---

CMakeLists.txt

Don't link to LLVM in SymEngineConfig.cmake

---

bin/install_travis.sh
symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/lambda_double.h
symengine/tests/cwrapper/test_cwrapper.c

Work-in-progress. Segfaulting right now:
```
#0  0x00000000005245f2 in SymEngine::Symbol::__eq__(SymEngine::Basic const&) const ()
#1  0x00000000004cfbd9 in SymEngine::LambdaDoubleVisitor<double>::bvisit(SymEngine::Symbol const&) ()
#2  0x00000000004ca9e6 in SymEngine::LambdaDoubleVisitor<double>::bvisit(SymEngine::Add const&) ()
#3  0x00000000004bafcc in lambda_real_double_visitor_init ()
#4  0x00000000004b05e8 in test_lambda_double ()
#5  0x00000000004a7d61 in main ()
```
will try again soon, but thought I should ask and see if it looks reasonable (once the test passes).
As you can see from the branch name my idea is to expose the LLVM visitor as well.

Add LambdaRealDoubleVisitor to cwrapper

---

.travis.yml
bin/install_travis.sh
bin/test_travis.sh
symengine/llvm_double.cpp
symengine/llvm_double.h

To fix #1385.
Tests passes locally with LLVM 5.0.
I'm new to the LLVM toolchain so a careful review is probably in place.
Do we want to add LLVM 5 to the CI runs?

Add support for LLVM5

---

symengine/dense_matrix.cpp
symengine/matrix.h
symengine/tests/matrix/test_matrix.cpp

I want LLVMDoubleVisitor to evaluate the elements of a DenseMatrix (in column major order).
Is this a sensible approach (pseudo-code):
```
jacobian(y, x, J)
LLVMDoubleVisitor v;
v.init(x, J.transpose().flat())
```
I didn't see an easy way to access `m_` of the jacobian matrix so I added `DenseMatrix::flat`.
But perhaps there's a better way?

Add DenseMatrix::flat (for use with LLVM visitor)

---

symengine/codegen.h
symengine/tests/printing/test_ccode.cpp

Such cases should be handled at compile-time due to constant folding by compilers
Relevant - #1383

Make ccode print acos(-1) for pi

---

symengine/llvm_double.cpp
symengine/llvm_double.h

~~Also I don't think we need to return a const string?~~ (didn't think about it being a reference).
EDIT: Maybe I should elaborate a little and give the underlying motivation:
When using [cereal](https://github.com/USCiLab/cereal) you can add serialization functions to your classes such as this one:
```
template <class Archive>
void save(Archive &ar) const {
ar(names, param_names, const_cast<se::LLVMDoubleVisitor&>(rhs_llvm).dumps(), ...);
}
```
Note the `const_cast`: it will no longer be needed after this PR.

Make dumps const (e.g. C++ lib cereal require const save methods)

---

CMakeLists.txt
symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/llvm_double.cpp
symengine/llvm_double.h
symengine/tests/cwrapper/test_cwrapper.c
symengine/tests/eval/test_lambda_double.cpp

I am currently working with some large systems of ordinary differential equations (chemical kinetics). I am working with hundreds of species and thousands of reactions. Number of rhs evaluations for a series of simulations is 1e7 (and 1e5 number of jacobian evaluations). The `LLVMDoubleVisitor` allows me to evaluate those expressions fast (~5 minutes), but the compilation of the expression takes 5x as much time. In this tentative PR I'm adding an options struct for turning on and off LLVM optimzation passes. Note also that I added a vectorization pass. I haven't evaluated the performance impact of that yet, will get back with data on that.
But I thought this was still a good point to take in some feedback on the API, what do you think?
EDIT: I glanced over [Julia's optimization …

[WIP] More LLVMDoubleVisitor settings

---

symengine/matrix.h
symengine/sparse_matrix.cpp
symengine/tests/matrix/test_matrix.cpp

Just as in the case of `DenseMatrix`, there was no easy way to access the elements of a `CSRMatrix`.
Also, I couldn't find a function for creating a sparse jacobian matrix, so I went ahead and implemented a static method: `CSRMatrix::jacobian`
Let me know what you think.

Add to CSRMatrix: jacobian, as_vectors & transpose 

---

cmake/FindARB.cmake

fmprb.h is not there in newer versions, but arb.h is in all versions
Fixes https://github.com/symengine/symengine/issues/1423

Look for arb.h instead of fmprb.h

---

symengine/dense_matrix.cpp
symengine/matrix.h
symengine/sparse_matrix.cpp
symengine/tests/matrix/test_matrix.cpp

This is a suggested change to add a constructor to DenseMatrix which accepts vec_basic. I propose that it is interpreted as column vector (I believe it's the convention and e.g. `jacobian` expects column vectors).
I also changed CSRMatrix::jacobian not to strictly require a pair of `DenseMatrix`s, but also accept `vec_basic` and `vec_sym`.
Let me know what you think.

DenseMatrix(vec_basic), CSRMatrix::jacobian(vec_basic, vec_sym)

---

symengine/tests/basic/test_arit.cpp
symengine/tests/basic/test_basic.cpp
symengine/tests/polynomial/test_uexprpoly.cpp
symengine/tests/polynomial/test_uratpoly.cpp
symengine/utilities/catch/.gitattributes
symengine/utilities/catch/catch.cpp
symengine/utilities/catch/catch.hpp

As the commit message says, support for std=c++17
random_shuffle was removed from std:: in c++17 (deprecated in c++14).
Excerpt from symengine build:
```
[ 41%] Building CXX object symengine/utilities/catch/CMakeFiles/catch.dir/catch.cpp.o
cd /conda-bld/symengine_1524567697988/work/build/symengine/utilities/catch && /conda-bld/symengine_1524567697988/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/clang++   -I/conda-bld/symengine_1524567697988/work -I/conda-bld/symengine_1524567697988/work/build -isystem /conda-bld/symengine_1524567697988/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p …
```

Update catch (support -std=c++17)

---

symengine/lambda_double.h
symengine/tests/eval/test_lambda_double.cpp

Fixes https://github.com/symengine/symengine.py/issues/234

Support for Piecewise in LambdaDoubleVisitor

---

CMakeLists.txt

This is logged in the cmake log, so need to print it.

Remove printing error log

---

symengine/utilities/catch/catch.cpp

In https://github.com/symengine/symengine/pull/1439 the code for printing stacktrace was removed. In that PR, catch changed from using signal to sigaction and then re-raising which means we can catch the signal that is re-raised and print the stacktrace

Print stack on segfault

---

symengine/llvm_double.cpp
symengine/tests/eval/test_lambda_double.cpp

When using lambdify with llvm backend, the expression `-abs(x)` results in `x` not `-x`, if you subs a negative number. I've added a testcase that triggers the bug.
I think I've also fixed it. Was there a reason why you didn't use llvm's `fabs`?

bug fix for -Abs(x) with llvm backend

---

symengine/symengine_assert.h

This PR rearranges the header in which the assertions are defined in order to make it a bit more understandable and to make the addition of further assertions easier. It also adds an assertion that takes an addition argument which is outputted as an error message to the console.

Tidy up assertions header + add an assertion with an error message

---

symengine/dict.h

If `dict.h` is included before some other headers, the compiler complains that `std::unordered_map` & co are undefined. This is corrected by adding these missing headers.

Add missing headers in dict.h

---

bin/release_authors.sh

This script can be used to obtain the list of authors who contributed to a
given release. The documentation how to use it is in the script itself.

Add release_authors.sh script

---

.travis.yml
bin/install_travis.sh

...looks like llvm-8 isn't on conda-forge yet:
https://github.com/conda-forge/llvm-meta-feedstock/pull/5
https://github.com/conda-forge/llvmdev-feedstock/pull/61

Try building with newly released LLVM-8

---

symengine/eval_mpfr.cpp
symengine/functions.cpp
symengine/tests/eval/test_eval_mpfr.cpp

Once we have an implementation of gamma and uppergamma, we can subtract
the two to make lowergamma. This constructs it with MPFR instead of
Symengine so that there is slightly less overhead.
Signed-off-by: Connor Behan <connor.behan@gmail.com>

Support LowerGamma with MPFR

---

.travis.yml
CMakeLists.txt

This is a workaround to https://github.com/symengine/symengine/issues/1516
With this change you can build in debug mode without Teuchos by passing `-DWITH_SYMENGINE_RCP=yes` to cmake.
cc @jppelteret

Allow symengine rcp even in debug mode 

---

symengine/llvm_double.cpp
symengine/tests/eval/test_lambda_double.cpp

From discussion on gitter:
> Pickling and unpickling the `LLVMDouble` (via symengine.py) does not correctly reset the `LLVMDoubleVisitor` that is supposed to be in `llvm_double[0]`. 
> 
> ### Reproducing the bug
> 
> 
> ```python
> from symengine import symbols
> x, y, z = symbols('x y z')
> ex = x**2 + y**2 + z**2
> from symengine import lambdify
> l = lambdify([x, y, z], [ex], backend='llvm')
> import pickle
> print('pickle.loads(pickle.dumps(l)) == l  :: ', pickle.loads(pickle.dumps(l)) == l)
> print(l.__reduce__())
> print(pickle.loads(pickle.dumps(l)).__reduce__())
> ```
> 
> gives 
> 
> ```python
> pickle.loads(pickle.dumps(l)) == l  ::  False
> (<built-in function llvm_loading_func>, (3, 1, [()], True, 1, 'C', [0, 1], <class 'numpy.float64'>, …
```

Fix LLVMDoubleVisitor load

---

symengine/visitor.h

Otherwise, clang emits
warning:
destructor called on non-final 'SymEngine::LambdaRealDoubleVisitor' that
has virtual functions but non-virtual destructor
[-Wdelete-non-virtual-dtor]

Add a virtual destructor to Visitor

---

benchmarks/parsing.cpp

Improve the output also. Now it prints:
```
$ ./benchmarks/parsing 
First call (initialization)
parse('0') = 0: 35us
Subsequent calls
8us 5us 4us 4us 5us 4us 4us 5us 4us 5us 
Single long benchmark
35ms
(x + y - sin(x)/(-4 + z**2) - x**(y**z))**5001
82ms
(x + y - sin(x)/(-4 + z**2) - x**(y**z))**5001
Repeated short benchmark
21ms
100ms
```
So one can see that the first call to `parse()` costs 35us, but subsequent calls cost ~ 5us. This is related to the changes introduced in #1593.

Verify that subsequent calls to parse() are fast

---

CMakeLists.txt
symengine/llvm_double.cpp
symengine/llvm_double.h

- requires c++14: add WITH_CPP14 option to CMake
- llvm::make_unique has been removed: alias it to std::make_unique

add support for LLVM 10

---

symengine/parser/parser.cpp
symengine/tests/basic/test_parser.cpp

Found during usage that "atan2" was being parsed as a `FunctionSymbol` rather than `ATan2`. Reading from type_codes.inc, there are a few others that are missing (e.g. GaloisField, Conjugate, Floor, Ceiling, and sets/Boolean operations) - not sure which of these would be desirable to include in the parser.

Parse atan2

---

symengine/CMakeLists.txt

Currently, the exported CMake target `symengine` does not have `INTERFACE_INCLUDE_DIRECTORIES` set. So I have to do this in a demo project:
```cmake
find_package(SymEngine CONFIG REQUIRED)
add_executable(symengine_test symengine_test.cpp)
target_include_directories(symengine_test PRIVATE ${SYMENGINE_INCLUDE_DIR})
target_link_libraries(symengine_test PRIVATE symengine)
```
With this patch, the `target_include_directories(symengine_test PRIVATE ${SYMENGINE_INCLUDE_DIR})` is unnecessary any more:
```cmake
find_package(SymEngine CONFIG REQUIRED)
add_executable(symengine_test symengine_test.cpp)
target_link_libraries(symengine_test PRIVATE symengine)
```

Add INTERFACE_INCLUDE_DIRECTORIES to the exported CMake target

---

symengine/dense_matrix.cpp
symengine/matrix.h
symengine/sparse_matrix.cpp
symengine/tests/matrix/test_matrix.cpp

Add non-virtual method ```is_square``` and virtual methods ```conjugate``` and ```conjugate_transpose``` to both ```DenseMatrix``` and ```CSRMatrix```.

Add conjugate, conjugate_transpose and is_square for matrices

---

symengine/llvm_double.cpp

- `DeadInstEliminationPass` has been removed from llvm trunk
- see https://reviews.llvm.org/D87933

use DeadCodeEliminationPass instead of DeadInstEliminationPass

---

symengine/dense_matrix.cpp
symengine/matrix.h
symengine/sparse_matrix.cpp
symengine/tests/matrix/test_matrix.cpp

Implement elementwise matrix multiplication for both ```DenseMatrix``` and ```CSRMatrix```
Addressing #1675

Add elementwise_mul_matrix method for Dense and CSR matrices

---

symengine/CMakeLists.txt
symengine/basic.h
symengine/dense_matrix.cpp
symengine/mul.cpp
symengine/number.h
symengine/pow.cpp
symengine/sparse_matrix.cpp
symengine/test_visitors.cpp
symengine/test_visitors.h
symengine/tests/basic/CMakeLists.txt
symengine/tests/basic/test_test_visitors.cpp

This is a reimplementation of the `is_zero` function. It can now return a `tribool` with an additional indeterminate value. It is implemented using a visitor, which so far doesn't have much more functionality than before, but has the potential. 
Future extension could be:
* Enable the visitor to use a context i.e. assumptions
* Other tests like `is_positive` and `is_real`
* More advanced zero-testing, e.g. for `mul` to check if any factor is zero etc

Add tribool type and update is_zero to return tribool

---

symengine/dense_matrix.cpp

The author of PR #1698 modified the code for is_zero in all the locations, however since #1651 was merged after that, the is_zero modification which had been made for all other functions by @rikardn was not there. This short PR fixes that issue.
Also, there is no `is_false(tribool x)`, would it be a good idea to have one, @isuruf ?

Fix broken test created by change in is_zero function

---

symengine/sparse_matrix.cpp
symengine/tests/matrix/test_matrix.cpp

- don't subtract 1 from an unsigned int that may be 0
- clear any existing data/indices before appending new values
- add test case copied from #1694
- resolves #1694

csr_binop_csr_canonical bugfixes

---

symengine/basic.h
symengine/number.h
symengine/test_visitors.cpp
symengine/test_visitors.h
symengine/tests/basic/test_basic.cpp
symengine/tests/basic/test_test_visitors.cpp

Add is_real function and more  helper functions for tribool.
The implementation of ```is_real``` is mostly trivial except for the visit of ```Add```. It uses the weak Kleene conjunction which is just a fancy name for what is called  ```fuzzy_group``` in sympy.

Add is_real function

---

symengine/dense_matrix.cpp
symengine/matrix.h
symengine/tests/matrix/test_matrix.cpp

Add the `is_weakly_diagonally_dominant` and `is_strictly_diagonally_dominant` member functions for `DenseMatrix`. The code for the two functions is duplicated except for one function call. I failed to find a way of avoiding code duplication that was as performant and easy to read.

Add tests for diagonal dominance for DenseMatrix

---

symengine/utilities/teuchos/Teuchos_stacktrace.cpp

these macros have been replaced with functions in newer versions of binutils: https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=fd3619828e94a24a92cddec42cbc0ab33352eeb4﻿

add support for newer versions of binutils - resolves #1712

---

symengine/dense_matrix.cpp
symengine/matrix.h
symengine/tests/matrix/test_matrix.cpp

Depending on PR #1707.
Implement the same algorithm as in sympy:
1. First "hermitify" (A + A.H) if non hermitian but square
2. Check if any non-positive diagonals. Shortcut to False in that case.
3. Check if diagonally dominant. Shortcut to True if True and only positive diagonals
4. If still undecided use gaussian elimination and check for positive diagonals
Most unit tests were copied from sympy.

is_positive_definite for DenseMatrix

---

symengine/lambda_double.h
symengine/tests/eval/test_lambda_double.cpp

- delete `LambdaRealDoubleVisitor` copy constructor as discussed here: https://github.com/symengine/symengine/pull/1680#issuecomment-682826644
- this resolves #1674
- add (initially failing) test of move-constructor
- test copied from https://github.com/symengine/symengine/pull/1673 but replacing copy construction with move construction
- test segfaults on this line: https://github.com/symengine/symengine/blob/master/symengine/lambda_double.h#L116
- fix segfault
- `return cse_intermediate_results[index]` in the lambda is presumably equivalent to `return *(cse_intermediate_results.data() + index);`
- if the `cse_intermediate_results` vector is moved from it is left in an undefined state, e.g. `cse_intermediate_results.data()` can be `NULL`
- so instead capture a direct pointer to the data …

Fix LambdaRealDoubleVisitor use-after-free issue

---

cmake/FindARB.cmake
cmake/LibFindMacros.cmake

Check for flint-arb

---

symengine/llvm_double.cpp

- rename `llvm.pow.f64.f64` -> `llvm.pow.f64`
- similarly for `pow.*`, `powi.*`, `maxnum.*`, `minnum.*`

fix naming of llvm intrinsics

---

symengine/symengine_rcp.h

This is necessary in order for code compiled with `clang -std=c++20` to include the symengine headers.
To reproduce the issue (sorry I wasn't sure how best to make a test for this):
```
mkdir build
cd build
cmake ..
make
echo "#include <symengine/visitor.h>" > test.cpp
clang++ -I. -I.. -std=c++20 -Wno-ambiguous-reversed-operator -c test.cpp
```
This generates the errors:
```
In file included from test.cpp:1:
../symengine/visitor.h:262:19: error: use of overloaded operator '!=' is ambiguous (with operand types 'SymEngine::RCP<const SymEngine::Basic>' and 'SymEngine::RCP<const SymEngine::Basic>')
if (farg1 != newarg1 or farg2 != newarg2) {
~~~~~ ^  ~~~~~~~
../symengine/type_codes.inc:63:1: note: in instantiation of function template specialization …
```

Mark `RCP<T>::operator!=` as const

---

.github/workflows/ci.yml
.github/workflows/coverage1.yml
.github/workflows/coverage2.yml

this seems to avoid the codecov upload issue without having to expose the codecov token (see #1752), although with more boilerplate yml.
(I also added a name to the build jobs to see more easily which job is which, but this is unrelated)

separate workflow for each coverage ci job

---

benchmarks/CMakeLists.txt
benchmarks/visitor_call.cpp
benchmarks/visitor_expressions.h
benchmarks/visitor_init.cpp

benchmark `init()` for
- `LambdaRealDoubleVisitor`
- `LLVMDoubleVisitor`
- `LLVMFloatVisitor`
also refactor visitor benchmarks
- move expressions to `visitor_expressions.h`
- add `SYMENGINE_BENCHMARK_VISITORS` macro to generate benchmarks for all expressions
and add more expressions
- two large expressions based on https://github.com/symengine/symengine/pull/1612
- one expression with many intrinsic functions copied from `test_lambda_double.cpp`

add visitor_init benchmark

---

symengine/printers/latex.cpp
symengine/tests/printing/test_printing.cpp

Fix symbols for Reals, Rationals and Integers sets in LaTeX printing. 
I.e. R now becomes 
instead of

Better symbols for number sets in LaTeX printing

---

symengine/CMakeLists.txt
symengine/assumptions.cpp
symengine/assumptions.h
symengine/number.h
symengine/test_visitors.cpp
symengine/test_visitors.h
symengine/tests/basic/CMakeLists.txt
symengine/tests/basic/test_assumptions.cpp
symengine/tests/basic/test_test_visitors.cpp

This PR adds the first version of an Assumptions class and use it in the `is_real` function.
* An assumptions object is constructed from symengine statements.
* The statements are parsed at construction into an internal form that is easier and faster to work with
* Methods on the assumptions object can be used to do basic queries on symbols. To for example check if a symbol is real.
* A function that wants to support assumptions can have an optional assumptions object argument.
* If no assumptions object is used default assumptions will be used
Benefits of design:
* Any symengine statements can be input as an assumption. The assumptions system can grow gradually and support more and more statements. For example `x > 0` would potentially mean that x is real and that x is positive and that …

Add Assumptions class

---

symengine/functions.cpp
symengine/tests/basic/test_functions.cpp

Automatic simplification of `floor(constant + integer)` to `integer`
Sympy does this automatically:
```python
>>> import sympy
>>> sympy.floor(sympy.pi + 4)
7
```
symengine (before this PR) did
```python
>>> import symengine
>>> symengine.floor(symengine.pi + 4)
floor(pi) + 4
```

Simplify floor(constant + integer) to integer

---

symengine/real_double.h
symengine/real_mpfr.cpp
symengine/tests/basic/test_arit.cpp

Fix the issue of `integer(0)` times a real number being real 0.0 instead of `integer(0)`. Both `real_double` and `real_mpfr` are fixed.

Let 0 * real be exactly 0 (fix #1559)

---

symengine/parser.h
symengine/parser/parser.cpp
symengine/parser/parser.h
symengine/tests/basic/test_parser.cpp

- local parser constants take precedence over built-in parser constants
- add a `parse_julia` function that uses "im" for `I`
- implemented as described in #1462

add optional local_parser_constants to Parser

---

symengine/number.h
symengine/test_visitors.cpp
symengine/test_visitors.h
symengine/tests/basic/test_test_visitors.cpp

Adding functions `is_rational` and `is_irrational`. Both are implemented using the same visitor.
non-exact numbers, e.g. `RealDouble`, are considered to be irrational. This is because almost all real numbers are irrational.

Add is_rational and is_irrational

---

.github/workflows/test_tutorials.yml

Setting the test tutorials workflow to "dispatch" since it is failing. When someone fixes it we can turn it on again.

Turn off test tutorials workflow

---

symengine/parser/generate_tokenizer_and_parser.sh

I didn't see the `WITH_GENERATE_PARSER` cmake option when I added this script﻿

remove generate parser script, duplicated existing `-DWITH_GENERATE_PARSER` cmake option

---

.github/workflows/ci.yml
bin/install_travis.sh
symengine/mp_boost.cpp
symengine/rational.cpp

- change boost version on CI to trigger #1639
- ci job [here](https://github.com/symengine/symengine/runs/2558611418?check_suite_focus=true#step:5:4363)
- fix unrelated compiler warning
- when `INTEGER_CLASS=boostmp` and denominator is negative, multiply top & bottom of rational by -1 to avoid this boost bug

fix #1639 boost rational number bug

---

symengine/complex_mpc.cpp
symengine/polys/uintpoly_piranha.h
symengine/polys/upolybase.h
symengine/series_flint.cpp
symengine/series_piranha.cpp
symengine/tests/basic/test_fields.cpp
symengine/tests/polynomial/test_uintpoly_flint.cpp
symengine/utilities/matchpycpp/bipartite.h
symengine/utilities/matchpycpp/hopcroft_karp.h

- suppress clang self-assignment warning for unit test with intentional self-assignment
- avoid unnecessary copies in loop variables (Wrange-loop-construct)
- don't move-return temporary objects (Wpessimizing-move)
- add missing 'override' (Winconsistent-missing-override)
- catch exception by reference
- make operator== symmetric (c++20 Wambiguous-reversed-operator)

fix compiler warnings

---

symengine/assumptions.cpp
symengine/assumptions.h
symengine/number.h
symengine/test_visitors.cpp
symengine/test_visitors.h
symengine/tests/basic/test_assumptions.cpp
symengine/tests/basic/test_test_visitors.cpp

This will replace #1790.
* Handle symbol equal to or not equal to zero in `Assumptions`
* Use assumptions in `is_zero` and `is_nonzero`
* throw exception for non-numeric expression in `is_zero` and `is_nonzero`

Assumptions for is_zero and is_nonzero

---

bin/install_travis.sh

hopefully this will fix CI build failures due to conda network problems﻿, e.g. https://github.com/symengine/symengine/runs/2597743050?check_suite_focus=true

CI: retry conda create command on error to workaround intermittent http issues

---

symengine/number.h
symengine/test_visitors.cpp
symengine/test_visitors.h
symengine/tests/basic/test_test_visitors.cpp

* Allow assumptions in `is_positive`, `is_negative`, `is_nonpositve` and `is_nonnegative`.
* Throw for non-numeric elements in expressions for these tests

Allow assumptions in is_positive etc

---

symengine/CMakeLists.txt
symengine/refine.cpp
symengine/refine.h
symengine/tests/basic/CMakeLists.txt
symengine/tests/basic/test_refine.cpp

As promised: A refine function that simplifies expressions given assumptions (like refine in mathematica https://reference.wolfram.com/language/ref/Refine.html and sympy https://docs.sympy.org/latest/modules/assumptions/refine.html). A modest start supporting `Abs`, `Sign`, `Floor`, `Ceiling` and `Conjugate`.

Add refine

---

bin/install_travis.sh
bin/test_travis.sh

I noticed that the CI in symengine.py [never reaches](https://github.com/bjodah/symengine.py/runs/2882747493#step:3:3038) the python tests due to sourcing of a bash script with "exit 0":
https://github.com/bjodah/symengine.py/blame/master/bin/test_symengine_unix.sh#L13
https://github.com/symengine/symengine/blob/master/bin/test_symengine_unix.sh#L33
Sourced scripts (and functions) in bash are allowed to "return", trying to use that in this PR.

bin/test_travis.sh is source'd by symengine.py test script

---

symengine/llvm_double.cpp

- this was implicitly assumed to be int32 in llvm <= 12
- appears to no longer be the case in llvm 13 (https://reviews.llvm.org/D99439)
Fixes the following segfault that occurs when running `test_lambda_double` compiled with llvm trunk:
```
File "/home/lkeegan/BIOQUANT/symengine/build/../symengine/utilities/catch/catch.cpp", line 24, in main()
int result = Catch::Session().run( argc, argv );
File "/home/lkeegan/BIOQUANT/symengine/build/../symengine/utilities/catch/catch.hpp", line 7185, in Catch::Session::run(int, char const* const*)
returnCode = run();
File "/home/lkeegan/BIOQUANT/symengine/build/../symengine/utilities/catch/catch.hpp", line 7220, in Catch::Session::run()
int exitCode = runInternal();
File "/home/lkeegan/BIOQUANT/symengine/build/../symengine/utilities/catch/catch.hpp", …
```

specify integer type of llvm powi 2nd argument

---

symengine/number.h
symengine/test_visitors.cpp
symengine/test_visitors.h
symengine/tests/basic/test_test_visitors.cpp

So far the basics is in. We could also consider using the `is_complex` as the same as `is_finite`.
Would be nice to at least have all the `is_` functions that sympy has to be more compatible

Add is_finite and is_infinite

---

.github/workflows/ci.yml
bin/install_travis.sh
symengine/llvm_double.cpp

fix for these warnings when running `./symengine/tests/eval/test_lambda_double` with llvm <= 12:
```
Intrinsic name not mangled correctly for type arguments! Should be: llvm.powi.f32
float (float, i32)* @llvm.powi.f32.i32﻿
```
(#1810 re-introduced this warning which was previously fixed in #1751)

only specify integer type of llvm powi 2nd argument for llvm version > 12

---

.github/workflows/ci.yml
symengine/CMakeLists.txt

- move cotire to end of CMakeLists.txt after all target properties (e.g. c++14) have been set
- re-enable cotire in ci jobs where it was disabled due to using c++ std > 11
- left it disabled for msan build as it causes other problems there

Fix cotire missing flags

---

symengine/CMakeLists.txt
symengine/set_funcs.cpp
symengine/sets.h
symengine/tests/basic/test_sets.cpp

Add functions `sup` and `inf` to calculate supremum and infimum for sets.
Implemented as plain functions and not member functions to keep the operations decoupled from the classes. This also allows using double dispatch.

Add sup and inf for sets

---

symengine/cwrapper.cpp

Currently we can't test this, because it's not supposed to throw an exception.
The only way an exception is triggered is if there's some bug in symengine
like #1828.

Fix exception handling for basic_diff

---

README.md

My PR to add a `symengine` recipe to the central conan repository was accepted: https://github.com/conan-io/conan-center-index/pull/7241.
It only includes the latest version (0.8.1), but I will try to update it with new versions as they are released.

Add conan installation method to README.

---

symengine/parser/sbml/sbml_parser.cpp
symengine/tests/basic/test_sbml_parser.cpp

- parse unknown zero-argument functions as function symbols instead of raising exception
- this is now consistent with what is done for functions with arguments

sbml parser: add support for zero arg function symbols

---

symengine/constants.cpp
symengine/eval_double.cpp
symengine/functions.cpp
symengine/functions.h
symengine/logic.cpp
symengine/parser/parser.cpp
symengine/parser/parser.h
symengine/parser/sbml/sbml_parser.cpp
symengine/parser/sbml/sbml_parser.h
symengine/prime_sieve.cpp
symengine/prime_sieve.h
symengine/printers/latex.cpp
symengine/printers/mathml.cpp
symengine/printers/sbml.cpp
symengine/printers/strprinter.cpp
symengine/printers/strprinter.h
symengine/printers/unicode.cpp
symengine/tests/ntheory/test_ntheory.cpp

When symengine is statically linked to a library, especially with link-time optimization, it can result in segfaults due to this issue: https://en.cppreference.com/w/cpp/language/siof
This PR tries to fix the instances I have found. It's possible I've missed some, but at least this is enough to avoid the issue in my use case involving pybind11 (527 valgrind errors from importing the python module reduced to 0).
Typically the fix is some form of the initialize-on-first-use idiom. For the constants, I introduced lambdas for this purpose to avoid having to add `()` to every reference to them in the code base.

Fixes for "static initialization order fiasco"

---

symengine/printers/stringbox.cpp
symengine/printers/unicode.cpp
symengine/tests/printing/test_printing.cpp

Compiling on Windows assumed regular string literals were 1252 encoded.

Specify u8 for string literals in unicode printer

---

symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/tests/cwrapper/test_cwrapper.c

There is a [https://github.com/symengine/symengine/pull/1829/](vector-based add) but no vector-based product

Product of n terms in cwrapper

---

symengine/lambda_double.h
symengine/llvm_double.cpp
symengine/llvm_double.h
symengine/tests/eval/test_lambda_double.cpp

Not sure if we should prefer constructing signaling or quiet NaNs.
If someone has an application where the payload is used, I guess we could support that too at some later point.

Support NaN in LLVM- and Lambda visitors

---

symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/tests/cwrapper/test_cwrapper.c

When freeing serialization string in C we get a const mismatch. I can see the point of having the serialized string as const, but it will require a cast for every free to avoid const-warnings. I remove a warning in the tests with this PR, but we should think about changing to non-const in the dump function to be able to free it with the free string function. Alternatively to have a separate free function for dumps.

Deconst to remove warning in tests compilation

---

symengine/logic.cpp
symengine/logic.h
symengine/tests/logic/test_logic.cpp

1. If there's a True condition, all conditions after are dropped.
2. False conditions are dropped.
3. If there's only one condition and it's True, the expression is returned
4. If the same condition is repeated, only the first one is kept.
5. If there are no conditions, a DomainError is thrown. This can happen if we evaluate a condition to False and it is dropped.
Fixes https://github.com/symengine/symengine.py/issues/393

Canonicalize Piecewise to remove redundant conditions

---

bin/install_travis.sh

This might fix the failing CI for the benchmark build. Version 1.7 of benchmark on conda have some issues with the libc++ being used.

Set version of benchmark package to 1.6.1

---

symengine/matrix.h

Make code clearer and avoid
```
overrides a member function but is not marked
'override' [-Winconsistent-missing-override]
```
in clang++

Use override for overriding member functions in matrix.h

---

symengine/simplify.cpp
symengine/simplify.h

This will be needed in the future, but triggers a warning when compiling with clang.

Remove unused assumptions from simplify class

---

symengine/mp_class.h
symengine/mp_wrapper.cpp

GMP supports custom allocators so the correct thing is to respect their allocation functions

Use the correct free function when printing GMP numbers

---

symengine/mp_class.h
symengine/tests/ntheory/test_ntheory.cpp

see symengine/symengine.py#428 and https://github.com/symengine/symengine.py/blob/f931a7bfde92c9a61545ff8f7343cf70203d6f45/symengine/tests/test_ntheory.py#L147

Handle denominator of zero explicitly for boost

---

symengine/CMakeLists.txt
symengine/basic-inl.h
symengine/basic.h
symengine/test_visitors.cpp
symengine/tests/basic/CMakeLists.txt
symengine/tests/basic/test_basic.cpp
symengine/tests/basic/test_tribool.cpp
symengine/tribool.h

* Change `tribool` from plain `enum` to safer `enum class`
* Move `tribool` to its own header `tribool.h`
* Add `or_tribool` and `orwk_tribool` for completeness
* Add tests for `tribool_from_bool`
* Fix bug that was found when moving to `enum class` for tribool

Tribool refactor

---

.github/workflows/build_doxygen.yml
.github/workflows/ci.yml
.github/workflows/test_tutorials.yml
symengine/llvm_double.cpp

- uwtable now takes a tablekind attribute
- see https://github.com/llvm/llvm-project/commit/6398903ac8c141820a84f3063b7956abe1742500
- resolves #1943
- also bump github actions checkout & cache versions in CI

fix run-time warnings when using llvm 15

---

bin/test_make_install.py
symengine/CMakeLists.txt

- add missing headers to cmake install
- see #1950

recursively check for missing headers in install in CI

---

.github/workflows/ci.yml
CMakeLists.txt
appveyor.yml
benchmarks/visitor_init.cpp
symengine/llvm_double.cpp
symengine/llvm_double.h
symengine/tests/eval/test_lambda_double.cpp

motivation: https://llvm.org/docs/NewPassManager.html#status-of-the-new-and-legacy-pass-managers
- use `PassBuilder` default `-O0`, `-O1`, ... passes instead of manually specifying passes
- remove `LLVMVisitor::init()` overloads with explicit list of passes
- add `passes` to SYMENGINE_LLVM_COMPONENTS in CMakeLists
- increase minimum required llvm version to 4.0
- remove llvm from USE_GLIBCXX_DEBUG ci job
- using debug libstdc++ changes the ABI: https://gcc.gnu.org/onlinedocs/libstdc++/manual/debug_mode_using.html
- but llvm library is not compiled against debug libstdc++
- new pass manager passes a vector between debug and non-debug translation units -> crash

use new llvm pass manager instead of legacy pass manager

---

CMakeLists.txt

See https://github.com/symengine/symengine/issues/1969#issuecomment-1679076896
Fixes https://github.com/symengine/symengine/issues/1969 and https://github.com/symengine/symengine/issues/1970

Check that INTEGER_CLASS=boostmp is not used with FLINT, ARB or MPFR

---

symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/tests/cwrapper/test_cwrapper.c

This is a try to expose the `has_symbol` function through the cwrapper so that I could be used in my work for LPython to implement symbolic algorithms as a part of ASR (https://github.com/lcompilers/lpython/pull/2336)

Exposing the `has_symbol` function through cwrapper.h

---

symengine/printers/sbml.cpp
symengine/tests/basic/test_sbml_parser.cpp

- If the last piece condition is `true` then don't explicitly print this condition
- This doesn't change symengine behaviour (other than sbml printing)
- Both forms are equivalent for the symengine sbml parser
- But it improves compatibility of the generated sbml string with the libSBML library
- libSBML parser returns `NaN` if multiple explicit piece conditions evaluate to `true`

Minor fix for SBML printing of piecewise function

---

symengine/llvm_double.cpp
symengine/llvm_double.h

- this implicity disables the `LLVMVisitor` copy constructors
- avoids segfault that occured if an initialized `LLVMVisitor` is copy assigned to
- (segfault itself looks like it may be a bug in LLVM)
- define default constructor/destructor in cpp file to avoid "incomplete type" compilation error
- resolves #1994

Use `unique_ptr` for `llvm::LLVMContext` and `llvm::ExecutionEngine`

---

symengine/cwrapper.cpp
symengine/cwrapper.h
symengine/tests/cwrapper/test_cwrapper.c

I saw that we didn't have a function `basic_sign` in the cwrapper and hence thought of it adding it.

Added support for sign function in the cwrapper

---

README.md

Hi!
While reviewing your upstream changes for inclusion of the new version in Conan Center Index in https://github.com/conan-io/conan-center-index/pull/24132 I saw that your install instructions were using the old Conan 1.
This new Conan 2 syntax installs the latest version available
Let me know if I should change anything if it fits better your style, thanks!

Add Conan 2 install instructions

---

README.md

The Gitter link points to sympy/symengine room which doesn’t seem to exist, so I changed it to symengine/symengine.

Fix Gitter link

---

symengine/matrices/transpose.cpp
symengine/tests/matrix/test_matrixexpr.cpp

Hi, this tiny PR fixes #2032. I replaced `ncols` with `nrows` as suggested in the issue and updated the corresponding test so that it now checks the transpose of a rectangular matrix rather than a square one.

Fix bug in transpose of ImmutableDenseMatrix

---

.github/workflows/ci.yml

- Add a job named `check`
- uses `re-actors/alls-green` action to pass if all build ci jobs passed and fail otherwise
- this can then be the only "required" ci job and list of "required" jobs doesn't need further updating in the future
- Reduce CI duplication, only run CI on pull requests or pushes to master branch
- previously PRs to the master branch would run every job twice, one for the branch, on for the PR
- Use ubuntu 24.04 for jobs using recent llvm

Improve CI maintainability

---

bin/install_travis.sh

This hopefully fixes the interpolation issue in the failing CI runs

Fix boost-cpp version in build script

---

CMakeLists.txt
README.md

Add support for the two remaining standard values of `CMAKE_BUILD_TYPE`: `RelWithDebInfo` and `MinSizeRel`.  This is particularly needed for Gentoo packaging that uses the most versatile `RelWithDebInfo` build variant for all packages.  See:
https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html

Support all standard values of CMAKE_BUILD_TYPE

---

CMakeLists.txt

else cmake sets it as absolute in cache but it should be kept relative for the install command

CMake: Set INSTALL_CMAKE_DIR as STRING

---

appveyor.yml
symengine/basic.cpp
symengine/dense_matrix.cpp
symengine/serialize-cereal.h
symengine/tests/basic/test_serialize-cereal.cpp

Before cereal <1.3.1, raw pointers were kept in the archive for serialization and deserialization of shared pointers. This internal detail was used for supporting RCP.
With 1.3.1, instead of raw pointers, std::shared_ptrs were stored. The workaround we added made cereal think that RCPs were unique_ptrs resulting in shared pointers being copied. for eg: sin(x) + cos(x) had two RCPs pointing to two different Symbols when loaded.
To fix this, we introduce a RCPBasicAware{Input,Output}Archive to wrap an Archive and keep RCPs alive to store and load expressions.

Fix serialization for shared pointers

---

CMakeLists.txt
cmake/SymEngineConfig.cmake.in

With cmake 4.0.0, having a minimum cmake version below 3.5 causes an error. This will affect any projects that depend on symengine and use the latest version of cmake.

Increase minimum cmake version.

---

symengine/prime_sieve.cpp
symengine/symengine_rcp.h

Starting with [gcc 15](https://github.com/gcc-mirror/gcc/blob/36c20fee22d40c6d25f52e929b42f5eab62cb1eb/libstdc%2B%2B-v3/include/c_global/ciso646#L49), a warning is emitted when including ciso646 with cppstd>=20. This becomes an error with -Werror.
The warning emitted by gcc recommends to include the <version> header instead. This commit does the for cppstd>17.

Conditionally include ciso646 on c++std<=17

---

.github/workflows/ci.yml
symengine/tests/basic/test_integer_class.cpp

PS: The original test contains two copies of
```
REQUIRE(mp_get_ui(integer_class("18446744073709551615"))
== 18446744073709551615u);
```
I changed the second one to "-18446744073709551615" because it feels like the author's original intention :)

Fixed failing tests when `long` is 32-bit #2107

---

bin/install_deps.sh

should help with CI run in symengine.py
see https://github.com/symengine/symengine.py/pull/482

avoid requiring too strict boost version
